# -*- coding: utf-8 -*-
"""Part 2: more intents + build JSON outputs."""
from __future__ import annotations

import importlib.util
import json
import sys
from copy import deepcopy
from pathlib import Path

ROOT = Path(__file__).resolve().parent
sys.path.insert(0, str(ROOT))

# Load part1
spec = importlib.util.spec_from_file_location("part1", ROOT / "_part1_intents.py")
part1 = importlib.util.module_from_spec(spec)
spec.loader.exec_module(part1)
L, qs, add, INTENTS = part1.L, part1.qs, part1.add, part1.INTENTS

# ===================== LICENSE =====================
add(
    intent_id="activate_license", category="License", priority="critical",
    description=L("فعال‌سازی License", "Activate license", "Активация License", "激活 License"),
    keywords=L(["فعال", "لایسنس", "activate", "registration", "کد", "bfxb", "bfxp", "bfxa"],
               ["activate", "license", "registration", "code", "bfxb", "bfxp", "bfxa", "claim"],
               ["активац", "лиценз", "registration", "код", "bfxb", "bfxp", "bfxa", "claim"],
               ["激活", "license", "registration", "代码", "bfxb", "bfxp", "bfxa", "claim"]),
    sample_questions=qs(
        ["چگونه لایسنس را فعال کنم؟", "فعال سازی کجاست؟", "لایسنس چطوری فعال میشه؟", "کد رو کجا بزنم؟",
         "Registration کجاست؟", "Activate کار نمیکنه", "کد نامعتبره", "claim چیه؟", "TX کجاست؟",
         "Device ID لازم؟", "از سایت فعال کنم یا برنامه؟", "Basic چطور؟", "Pro چطور؟", "AI چطور؟",
         "بعد از پرداخت چی؟", "کد CLM چیه؟", "چرا Limited Access؟", "My Code نمیاد", "Reactivation فرق داره؟",
         "فعال‌سازی انجام نمی‌شود"],
        ["How can I activate my license?", "Where is activation?", "License doesn't work", "Where paste code?",
         "Registration tab?", "Invalid code", "What is claim?", "TX hash where?", "Need Device ID?",
         "Website or in-app?", "Activate Basic", "Activate Pro", "Activate AI Pro", "After payment?",
         "CLM code?", "Limited Access why?", "My Code empty", "Reactivation vs activate", "Code not working",
         "Unlock features"],
        ["Как активировать лицензию?", "Где активация?", "Лицензия не активируется", "Куда вставить код?",
         "Вкладка Registration?", "Неверный код", "Что такое claim?", "Где TX?", "Нужен Device ID?",
         "Сайт или приложение?", "Активировать Basic", "Активировать Pro", "AI Pro", "После оплаты?",
         "Код CLM?", "Почему Limited Access?", "My Code пусто", "Reactivation", "Код не работает",
         "Разблокировать функции"],
        ["如何激活License？", "激活在哪里？", "License激活不了", "代码粘贴哪里？",
         "Registration标签？", "无效代码", "什么是claim？", "TX在哪？", "需要Device ID吗？",
         "网站还是应用内？", "激活Basic", "激活Pro", "激活AI Pro", "付款后怎么办？",
         "CLM码？", "为何Limited Access？", "My Code为空", "Reactivation", "代码无效",
         "解锁功能"],
    ),
    short=L("تب Registration → Device ID را کپی → کد/claim را Activate کنید.",
            "Open Registration → copy Device ID → paste code/claim → Activate.",
            "Registration → скопируйте Device ID → вставьте код/claim → Activate.",
            "打开 Registration → 复制 Device ID → 粘贴代码/claim → Activate。"),
    full=L("پیشوندها: BFXB Basic، BFXP Pro، BFXA AI Pro، BFXQ سهمیه AI. کدهای claim معمولاً `-CLM-` دارند و Device ID را bind می‌کنند. قیمت زنده از license-access؛ اختراع نکنید.",
           "Prefixes: BFXB Basic, BFXP Pro, BFXA AI Pro, BFXQ AI quota. Claim codes often include `-CLM-` and bind Device ID. Prefer live license-access prices.",
           "Префиксы: BFXB/BFXP/BFXA/BFXQ. Claim часто с `-CLM-` и привязкой Device ID. Цены — live catalog.",
           "前缀：BFXB/BFXP/BFXA/BFXQ。claim 常含 `-CLM-` 并绑定 Device ID。价格以线上目录为准。"),
    expert=L("مسیر TX/password و Reactivation جداست. بعد از claim، TX معمولاً کد را دوباره نشان نمی‌دهد.",
             "TX/password and Reactivation are separate paths. After claim, TX usually won't reprint codes.",
             "Пути TX/password и Reactivation отдельные. После claim TX обычно не показывает коды снова.",
             "TX/password 与 Reactivation 为不同路径。claim 后 TX 通常不再显示代码。"),
    steps=L(["۱. Registration", "۲. کپی Device ID", "۳. خرید/claim در foxnext.net", "۴. Paste → Activate", "۵. View را در صورت نیاز عوض کنید"],
            ["1. Registration", "2. Copy Device ID", "3. Buy/claim on foxnext.net", "4. Paste → Activate", "5. Switch View if needed"],
            ["1. Registration", "2. Device ID", "3. Покупка/claim на foxnext.net", "4. Paste → Activate", "5. Смените View при необходимости"],
            ["1. Registration", "2. 复制 Device ID", "3. 在 foxnext.net 购买/claim", "4. 粘贴 → Activate", "5. 必要时切换 View"]),
    errors=L(["invalid code", "claim already bound", "TX used", "tier mismatch"],
             ["invalid code", "claim already bound", "TX used", "tier mismatch"],
             ["invalid code", "claim already bound", "TX used", "tier mismatch"],
             ["invalid code", "claim already bound", "TX used", "tier mismatch"]),
    solutions=L(["کد کامل را دوباره کپی", "Device ID درست", "Reactivation", "پشتیبانی با Device ID"],
                ["Re-copy full code", "Correct Device ID", "Reactivation", "Support with Device ID"],
                ["Скопируйте код полностью", "Верный Device ID", "Reactivation", "Поддержка с Device ID"],
                ["完整重贴代码", "确认 Device ID", "Reactivation", "带 Device ID 找支持"]),
    related=["device_id", "claim_code", "reactivation", "need_activate", "pricing"],
    clarifying=L(["کدام سطح را می‌خواهید: Basic، Pro یا AI Pro؟", "کد دارید یا TX پرداخت؟"],
                 ["Which tier: Basic, Pro, or AI Pro?", "Do you have a code or a payment TX?"],
                 ["Какой тариф: Basic, Pro или AI Pro?", "Есть код или TX оплаты?"],
                 ["要 Basic、Pro 还是 AI Pro？", "你有代码还是付款 TX？"]),
    faq_refs=["Q031", "Q032", "Q102", "Q188"],
)

add(
    intent_id="device_id", category="License", priority="high",
    description=L("Device ID", "Device ID", "Device ID", "Device ID"),
    keywords=L(["device id", "شناسه دستگاه", "system id", "fingerprint"],
               ["device id", "system id", "license id", "fingerprint"],
               ["device id", "system id", "идентификатор"],
               ["device id", "设备id", "system id"]),
    sample_questions=qs(
        ["Device ID کجاست؟", "شناسه دستگاه چیه؟", "System ID؟", "چطور کپی کنم؟", "برای فعال‌سازی لازمه؟",
         "عوض کردن ویندوز Device ID عوض میشه؟", "به پشتیبانی بدم؟", "License ID همونه؟", "گمش کردم؟",
         "روی Registration هست؟", "اندروید هم داره؟", "چرا لازم؟", "claim به چی bind میشه؟", "طولانیه؟",
         "فاصله/خط تیره داره؟", "اشتباه کپی کردم؟", "دو تا Device ID؟", "بعد از نصب دوباره؟",
         "Reactivation با همونه؟", "کجا نشون میده؟"],
        ["Where is Device ID?", "What is Device ID?", "System ID?", "How to copy?", "Needed for activation?",
         "Changes after Windows reinstall?", "Send to support?", "Same as License ID?", "Lost it?",
         "On Registration?", "Android too?", "Why needed?", "Claim binds to what?", "Format?",
         "Copy wrong?", "Two device IDs?", "After reinstall?", "Reactivation uses it?", "Where shown?", "Fingerprint?"],
        ["Где Device ID?", "Что такое Device ID?", "System ID?", "Как копировать?", "Нужен для активации?",
         "Меняется после переустановки Windows?", "Отправить в поддержку?", "Это License ID?", "Потерял?",
         "На Registration?", "На Android?", "Зачем?", "К чему bind claim?", "Формат?",
         "Неверно скопировал?", "Два Device ID?", "После переустановки?", "Reactivation?", "Где видно?", "Fingerprint?"],
        ["Device ID在哪？", "什么是Device ID？", "System ID？", "怎么复制？", "激活需要吗？",
         "重装Windows会变吗？", "发给支持？", "等于License ID吗？", "丢了？",
         "在Registration？", "Android也有？", "为什么需要？", "claim绑定什么？", "格式？",
         "复制错了？", "两个Device ID？", "重装后？", "Reactivation用它？", "在哪显示？", "指纹？"],
    ),
    short=L("Device ID اثرانگشت دستگاه برای bind لایسنس است؛ در تب Registration دیده می‌شود.",
            "Device ID is the machine fingerprint for license binding; shown on Registration.",
            "Device ID — отпечаток устройства для привязки лицензии; на вкладке Registration.",
            "Device ID 是用于绑定 License 的设备指纹，在 Registration 显示。"),
    full=L("برای claim و پشتیبانی لازم است. سخت‌افزار/نصب مجدد ممکن است bind را بشکند → Reactivation.",
           "Required for claim and support. Hardware/OS reinstall may break binding → use Reactivation.",
           "Нужен для claim и поддержки. Смена железа/ОС может сломать привязку → Reactivation.",
           "用于 claim 与支持。更换硬件/重装系统可能破坏绑定 → 使用 Reactivation。"),
    expert=L("با AI status checks هم استفاده می‌شود. هرگز Device ID جعلی نسازید.",
             "Also used in AI status checks. Never invent a Device ID.",
             "Также в AI status checks. Не выдумывайте Device ID.",
             "也用于 AI 状态检查。不要编造 Device ID。"),
    steps=L(["۱. تب Registration", "۲. Device ID را کپی", "۳. در Activation سایت بچسبانید", "۴. برای تیکت به پشتیبانی بفرستید"],
            ["1. Registration tab", "2. Copy Device ID", "3. Paste on website Activation", "4. Include in support tickets"],
            ["1. Registration", "2. Скопируйте Device ID", "3. Вставьте на сайте Activation", "4. Приложите в тикет"],
            ["1. Registration", "2. 复制 Device ID", "3. 粘贴到网站 Activation", "4. 工单中附上"]),
    errors=L(["کپی ناقص", "دستگاه عوض شده"], ["Partial copy", "Device changed"],
             ["Неполное копирование", "Сменилось устройство"], ["复制不完整", "设备变更"]),
    solutions=L(["دوباره کپی کامل", "Reactivation"], ["Recopy full ID", "Reactivation"],
                ["Скопируйте полностью", "Reactivation"], ["完整重复制", "Reactivation"]),
    related=["activate_license", "reactivation", "contact_support"],
    clarifying=L(["Windows است یا Android؟", "فعال‌سازی می‌کنید یا تیکت پشتیبانی؟"],
                 ["Windows or Android?", "Activating or contacting support?"],
                 ["Windows или Android?", "Активация или поддержка?"],
                 ["Windows 还是 Android？", "是在激活还是联系支持？"]),
    faq_refs=["Q035", "Q190"],
)

add(
    intent_id="claim_code", category="License", priority="high",
    description=L("کد claim", "Claim code", "Claim-код", "Claim 码"),
    keywords=L(["claim", "clm", "سایت", "بایند"], ["claim", "clm", "website", "bound"],
               ["claim", "clm", "привяз"], ["claim", "clm", "绑定"]),
    sample_questions=qs(
        ["کد claim چیه؟", "CLM یعنی چی؟", "claim already bound؟", "اولین فعال‌سازی؟", "با Device ID؟",
         "از سایت میاد؟", "با BFXB فرق داره؟", "دوباره استفاده؟", "TX بعد claim؟", "کد کامل؟",
         "فاصله‌ها مهمه؟", "اشتباه سطح؟", "Basic claim روی Pro؟", "منقضی؟", "کپی از ایمیل؟",
         "ربات کد میده؟", "PAS؟", "یک‌بار مصرفه؟", "خطا bound یعنی؟", "چیکار کنم اگر bound شد؟"],
        ["What is claim code?", "What is CLM?", "claim already bound?", "First unlock?", "Needs Device ID?",
         "From website?", "Vs full BFXB?", "Reuse?", "TX after claim?", "Full code?",
         "Spaces matter?", "Wrong tier?", "Basic claim on Pro?", "Expired?", "From email?",
         "Bot gives code?", "PAS?", "One-time?", "Bound meaning?", "What if already bound?"],
        ["Что такое claim?", "Что такое CLM?", "claim already bound?", "Первая активация?", "Нужен Device ID?",
         "С сайта?", "Отличие от BFXB?", "Повторно?", "TX после claim?", "Полный код?",
         "Пробелы?", "Неверный тариф?", "Basic claim на Pro?", "Истёк?", "Из письма?",
         "Бот даёт код?", "PAS?", "Одноразовый?", "Что значит bound?", "Если уже bound?"],
        ["什么是claim码？", "CLM是什么？", "claim already bound？", "首次解锁？", "要Device ID吗？",
         "来自网站？", "和完整BFXB区别？", "能复用吗？", "claim后的TX？", "完整代码？",
         "空格重要吗？", "层级错了？", "Basic claim用于Pro？", "过期？", "来自邮件？",
         "机器人给码？", "PAS？", "一次性？", "bound含义？", "已经bound怎么办？"],
    ),
    short=L("کد claim (مثلاً با `-CLM-`) در اولین Activate به Device ID وصل می‌شود.",
            "Claim codes (often with `-CLM-`) bind to Device ID on first Activate.",
            "Claim-коды (часто с `-CLM-`) привязываются к Device ID при первом Activate.",
            "Claim 码（常含 `-CLM-`）在首次 Activate 时绑定 Device ID。"),
    full=L("اگر already bound شد، روی همان دستگاه Reactivation کنید یا با Device ID به پشتیبانی بروید؛ انتظار چاپ دوباره از TX نداشته باشید.",
           "If already bound, use Reactivation on that device or support with Device ID; don't expect TX to reprint codes.",
           "Если already bound — Reactivation на том же устройстве или поддержка с Device ID.",
           "若 already bound：在原设备 Reactivation，或带 Device ID 找支持；别指望 TX 再次显示代码。"),
    expert=L("سطح کد باید با دکمه Activate همان سطح جور باشد (Basic/Pro/AI).",
             "Code tier must match the Activate action (Basic/Pro/AI).",
             "Тариф кода должен совпадать с кнопкой Activate.",
             "代码层级须与 Activate 操作的层级一致。"),
    steps=L(["۱. Device ID", "۲. کد claim کامل", "۳. Activate همان سطح", "۴. اگر bound بود Reactivation"],
            ["1. Device ID", "2. Full claim code", "3. Matching Activate", "4. If bound → Reactivation"],
            ["1. Device ID", "2. Полный claim", "3. Нужный Activate", "4. Если bound → Reactivation"],
            ["1. Device ID", "2. 完整 claim 码", "3. 对应层级 Activate", "4. 若 bound → Reactivation"]),
    errors=L(["claim already bound", "invalid", "tier mismatch"],
             ["claim already bound", "invalid", "tier mismatch"],
             ["claim already bound", "invalid", "tier mismatch"],
             ["claim already bound", "invalid", "tier mismatch"]),
    solutions=L(["Reactivation", "کد درست سطح", "پشتیبانی"],
                ["Reactivation", "Correct tier code", "Support"],
                ["Reactivation", "Код нужного тарифа", "Поддержка"],
                ["Reactivation", "正确层级代码", "支持"]),
    related=["activate_license", "device_id", "reactivation"],
    clarifying=L(["متن دقیق خطا چیست؟", "روی همان PC اول فعال کردید؟"],
                 ["Exact error text?", "Did you first activate on this PC?"],
                 ["Точный текст ошибки?", "Первая активация была на этом ПК?"],
                 ["确切错误原文？", "是否在本机首次激活？"]),
    faq_refs=["Q032", "Q045", "Q158"],
)

add(
    intent_id="reactivation", category="License", priority="high",
    description=L("Reactivation", "Reactivation", "Reactivation", "Reactivation"),
    keywords=L(["reactiv", "بازیابی", "نصب مجدد", "restore"],
               ["reactivation", "restore", "reinstall", "recover"],
               ["reactiv", "восстанов", "переустанов"],
               ["reactiv", "恢复", "重装"]),
    sample_questions=qs(
        ["Reactivation چیه؟", "ویندوز عوض کردم لایسنس؟", "چطور برگردونم؟", "not found؟", "expired؟",
         "کد از سرور میاد؟", "Device ID همون؟", "بعد فرمت؟", "PC جدید؟", "tier mismatch؟",
         "جای Activate؟", "اینترنت لازم؟", "هاب قطع؟", "Proxy؟", "موفق شد چی میشه؟",
         "My Code پر میشه؟", "چند بار؟", "اندروید؟", "پشتیبانی کی؟", "restore license"],
        ["What is Reactivation?", "Windows reinstalled?", "How restore?", "not found?", "expired?",
         "Code from server?", "Same Device ID?", "After format?", "New PC?", "tier mismatch?",
         "Instead of Activate?", "Need internet?", "Hub down?", "Proxy?", "On success?",
         "My Code fills?", "How many times?", "Android?", "When support?", "restore license"],
        ["Что такое Reactivation?", "Переустановил Windows?", "Как восстановить?", "not found?", "expired?",
         "Код с сервера?", "Тот же Device ID?", "После формата?", "Новый ПК?", "tier mismatch?",
         "Вместо Activate?", "Нужен интернет?", "Хаб недоступен?", "Proxy?", "При успехе?",
         "My Code заполнится?", "Сколько раз?", "Android?", "Когда в поддержку?", "restore license"],
        ["什么是Reactivation？", "重装Windows了？", "如何恢复？", "not found？", "expired？",
         "服务器返回代码？", "同一Device ID？", "格式化后？", "新电脑？", "tier mismatch？",
         "代替Activate？", "需要联网？", "Hub不通？", "Proxy？", "成功后？",
         "My Code会填吗？", "可几次？", "Android？", "何时找支持？", "restore license"],
    ),
    short=L("Reactivation لایسنس قبلی را از هاب با Device ID برمی‌گرداند.",
            "Reactivation restores a prior license from the hub using Device ID.",
            "Reactivation восстанавливает лицензию с хаба по Device ID.",
            "Reactivation 通过 Device ID 从 Hub 恢复先前 License。"),
    full=L("نتایج رایج: success، not found، expired، tier mismatch. اینترنت/Proxy لازم است.",
           "Common outcomes: success, not found, expired, tier mismatch. Needs internet/Proxy.",
           "Исходы: success, not found, expired, tier mismatch. Нужен интернет/Proxy.",
           "常见结果：success、not found、expired、tier mismatch。需要联网/Proxy。"),
    expert=L("اگر دستگاه واقعاً عوض شده، ممکن است bind جدید یا پشتیبانی لازم باشد.",
             "If the machine truly changed, new binding or support may be required.",
             "Если устройство реально другое — новая привязка или поддержка.",
             "若设备确实更换，可能需要重新绑定或联系支持。"),
    steps=L(["۱. Registration → Reactivation", "۲. اینترنت/Proxy", "۳. نتیجه را بخوانید", "۴. در صورت نیاز پشتیبانی + Device ID"],
            ["1. Registration → Reactivation", "2. Internet/Proxy", "3. Read result", "4. Support + Device ID if needed"],
            ["1. Registration → Reactivation", "2. Интернет/Proxy", "3. Прочитайте результат", "4. Поддержка + Device ID"],
            ["1. Registration → Reactivation", "2. 网络/Proxy", "3. 查看结果", "4. 必要时支持 + Device ID"]),
    errors=L(["not found", "expired", "tier mismatch", "hub unreachable"],
             ["not found", "expired", "tier mismatch", "hub unreachable"],
             ["not found", "expired", "tier mismatch", "hub unreachable"],
             ["not found", "expired", "tier mismatch", "hub unreachable"]),
    solutions=L(["Proxy", "Activate با کد", "پشتیبانی"], ["Proxy", "Activate with code", "Support"],
                ["Proxy", "Activate с кодом", "Поддержка"], ["Proxy", "用代码 Activate", "支持"]),
    related=["device_id", "activate_license", "proxy_settings"],
    clarifying=L(["ویندوز را عوض کردید یا فقط برنامه را؟", "پیام دقیق Reactivation؟"],
                 ["Did you reinstall Windows or only the app?", "Exact Reactivation message?"],
                 ["Переустановили Windows или только приложение?", "Точное сообщение Reactivation?"],
                 ["是重装了 Windows 还是只重装应用？", "Reactivation 确切提示？"]),
    faq_refs=["Q034", "Q157"],
)

add(
    intent_id="pricing", category="License", priority="medium",
    description=L("قیمت‌گذاری", "Pricing", "Цены", "价格"),
    keywords=L(["قیمت", "هزینه", "usdt", "چقدر"], ["price", "cost", "usdt", "how much"],
               ["цена", "стоимость", "usdt", "сколько"], ["价格", "多少钱", "usdt"]),
    sample_questions=qs(
        ["Basic چند؟", "Pro چند؟", "AI چند؟", "همیشه ۱۹/۳۳/۴۰؟", "چند ماهه؟",
         "تخفیف چند دستگاه؟", "کاتالوگ کجاست؟", "BEP-20؟", "شارژ AI جدا؟", "قیمت زنده؟",
         "fallback چیه؟", "ارز دیگه؟", "۱۸ ماه؟", "۱۲ تا ۳۰؟", "device2 تخفیف؟",
         "از کجا بخرم؟", "PAS قیمت؟", "اشتباه مبلغ TX؟", "هاب قیمت نمیاره؟", "پشتیبانی قیمت؟"],
        ["Basic price?", "Pro price?", "AI price?", "Always 19/33/40?", "How many months?",
         "Multi-device discount?", "Where catalog?", "BEP-20?", "AI quota separate?", "Live price?",
         "Fallback amounts?", "Other currency?", "18 months?", "12-30 months?", "device2 discount?",
         "Where buy?", "Wrong TX amount?", "Hub price fail?", "Support for price?", "USDT only?"],
        ["Цена Basic?", "Цена Pro?", "Цена AI?", "Всегда 19/33/40?", "Сколько месяцев?",
         "Скидка на устройства?", "Где каталог?", "BEP-20?", "AI quota отдельно?", "Live цена?",
         "Fallback?", "Другая валюта?", "18 месяцев?", "12–30?", "device2?",
         "Где купить?", "Неверная сумма TX?", "Хаб не отдаёт цены?", "Поддержка по цене?", "Только USDT?"],
        ["Basic多少钱？", "Pro多少钱？", "AI多少钱？", "永远19/33/40吗？", "几个月？",
         "多设备折扣？", "目录在哪？", "BEP-20？", "AI quota另算？", "实时价格？",
         "fallback？", "其他货币？", "18个月？", "12-30？", "device2折扣？",
         "哪里买？", "TX金额错？", "Hub取不到价？", "价格咨询支持？", "仅USDT？"],
    ),
    short=L("قیمت زنده از کاتالوگ هاب است؛ مبالغ ۱۹/۳۳/۴۰ فقط fallback کد هستند.",
            "Live prices come from the hub catalog; 19/33/40 are code fallbacks only.",
            "Живые цены из каталога хаба; 19/33/40 — лишь fallback в коде.",
            "实时价格以 Hub 目录为准；19/33/40 只是代码 fallback。"),
    full=L("license-access: ماه‌های ۱۲–۳۰، تا ۳ دستگاه با تخفیف. AI quota جدا. پرداخت را با مبلغ روی صفحه جور کنید.",
           "license-access: months 12–30, up to 3 devices with discounts. AI quota separate. Pay the on-screen amount.",
           "license-access: месяцы 12–30, до 3 устройств со скидками. AI quota отдельно. Платите сумму на экране.",
           "license-access：12–30 个月，最多 3 台设备折扣。AI quota 另计。按页面金额支付。"),
    expert=L("اگر fetch قیمت شکست بخورد، ممکن است به پشتیبانی ارجاع داده شوید (@HiBlackFoxVpn).",
             "If price fetch fails, UI may point users to support (@HiBlackFoxVpn).",
             "Если цены не загрузились — возможна отсылка в поддержку (@HiBlackFoxVpn).",
             "若价格拉取失败，界面可能引导联系支持（@HiBlackFoxVpn）。"),
    steps=L(["۱. صفحه Activation/کاتالوگ زنده", "۲. ماه و سطح را انتخاب", "۳. مبلغ دقیق را بپردازید", "۴. Activate"],
            ["1. Live Activation/catalog", "2. Pick months & tier", "3. Pay exact amount", "4. Activate"],
            ["1. Live Activation/каталог", "2. Месяцы и тариф", "3. Точная сумма", "4. Activate"],
            ["1. 查看线上 Activation/目录", "2. 选择月数与层级", "3. 支付准确金额", "4. Activate"]),
    errors=L(["wrong amount", "price fetch fail"], ["wrong amount", "price fetch fail"],
             ["wrong amount", "price fetch fail"], ["wrong amount", "price fetch fail"]),
    solutions=L(["مبلغ صفحه", "تماس پشتیبانی"], ["On-screen amount", "Contact support"],
                ["Сумма с экрана", "Поддержка"], ["按页面金额", "联系支持"]),
    related=["activate_license", "ai_quota", "contact_support"],
    clarifying=L(["کدام سطح و چند ماه؟", "مبلغ روی صفحه چقدر است؟"],
                 ["Which tier and months?", "What amount is shown on screen?"],
                 ["Какой тариф и месяцы?", "Какая сумма на экране?"],
                 ["哪个层级、几个月？", "页面显示金额是多少？"]),
    faq_refs=["Q038", "Q039", "Q040", "Q156"],
)

print("after license", len(INTENTS))

# Persist intermediate for part3
(ROOT / "_intents_state.json").write_text(
    json.dumps({"count": len(INTENTS)}, ensure_ascii=False), encoding="utf-8"
)
