# -*- coding: utf-8 -*-
"""Part 3: deploy/ops/errors intents + emit JSON database files."""
from __future__ import annotations

import importlib.util
import json
import sys
from copy import deepcopy
from pathlib import Path

ROOT = Path(__file__).resolve().parent
OUT = ROOT / "intents"
OUT.mkdir(parents=True, exist_ok=True)

spec = importlib.util.spec_from_file_location("part2", ROOT / "_part2_intents.py")
part2 = importlib.util.module_from_spec(spec)
# part2 loads part1
sys.path.insert(0, str(ROOT))
spec.loader.exec_module(part2)
L, qs, add, INTENTS = part2.L, part2.qs, part2.add, part2.INTENTS

# ===================== DEPLOY / SSH =====================
add(
    intent_id="first_run_path", category="GettingStarted", priority="critical",
    description=L("مسیر اولین اجرا", "First-run path", "Первый запуск", "首次运行路径"),
    keywords=L(["شروع", "اول", "مبتدی", "راهنما"], ["first run", "beginner", "start", "getting started"],
               ["первый", "новичок", "старт"], ["首次", "新手", "开始"]),
    sample_questions=qs(
        ["از کجا شروع کنم؟", "قدم اول چیه؟", "مبتدی چیکار کنه؟", "ترتیب درست؟", "بعد نصب چی؟",
         "Central اول؟", "SSH قبل Deploy؟", "بدون لایسنس چی؟", "Exit کی؟", "Panel Info کی؟",
         "زبان اول؟", "حالت Basic؟", "VPS لازم؟", "Partners کجا؟", "اشتباهات رایج؟",
         "مسیر پیشنهادی؟", "آموزش سریع", "چک‌لیست", "بعد Full Deploy؟", "کی Pro بخرم؟"],
        ["Where do I start?", "First steps?", "Beginner path?", "Correct order?", "After install?",
         "Central first?", "SSH before Deploy?", "Without license?", "When exits?", "When Panel Info?",
         "Language first?", "Pick Basic?", "Need VPS?", "Partners where?", "Common mistakes?",
         "Recommended path?", "Quick tutorial", "Checklist", "After Full Deploy?", "When buy Pro?"],
        ["С чего начать?", "Первые шаги?", "Путь новичка?", "Правильный порядок?", "После установки?",
         "Сначала Central?", "SSH до Deploy?", "Без лицензии?", "Когда Exit?", "Когда Panel Info?",
         "Сначала язык?", "Выбрать Basic?", "Нужен VPS?", "Где Partners?", "Частые ошибки?",
         "Рекомендуемый путь?", "Быстрый гайд", "Чеклист", "После Full Deploy?", "Когда покупать Pro?"],
        ["从哪开始？", "第一步？", "新手路径？", "正确顺序？", "安装后？",
         "先Central？", "Deploy前先SSH？", "无License能做什么？", "何时加Exit？", "何时看Panel Info？",
         "先选语言？", "选Basic？", "需要VPS吗？", "Partners在哪？", "常见错误？",
         "推荐路径？", "快速教程", "清单", "Full Deploy之后？", "何时买Pro？"],
    ),
    short=L("Basic → Central Setup → Connect SSH → Full Deploy → Panel Login Info؛ Exit بعد از فعال‌سازی.",
            "Basic → Central Setup → Connect SSH → Full Deploy → Panel Login Info; exits after activation.",
            "Basic → Central Setup → Connect SSH → Full Deploy → Panel Login Info; Exit после активации.",
            "Basic → Central Setup → Connect SSH → Full Deploy → Panel Login Info；激活后再加 Exit。"),
    full=L("VPS را از FoxNext → Partners بخرید. این برنامه کلاینت وب‌گردی نیست. از Connect SSH قبل از Full Deploy رد نشوید.",
           "Buy VPS via FoxNext → Partners. This is not a browse VPN client. Never skip Connect SSH before Full Deploy.",
           "VPS через FoxNext → Partners. Это не VPN-клиент для серфинга. Не пропускайте Connect SSH перед Full Deploy.",
           "通过 FoxNext → Partners 购买 VPS。这不是上网 VPN 客户端。Full Deploy 前不要跳过 Connect SSH。"),
    expert=L("منبع 3X-UI را بر اساس شبکه انتخاب کنید: Hub یا Local اگر GitHub بسته است.",
             "Pick 3X-UI source by network: Hub or Local if GitHub is blocked.",
             "Источник 3X-UI по сети: Hub или Local, если GitHub недоступен.",
             "按网络选择 3X-UI 来源：GitHub 不通时用 Hub 或 Local。"),
    steps=L(["۱. Setup از foxnext.net", "۲. زبان + Basic", "۳. Central", "۴. Connect SSH", "۵. Full Deploy", "۶. Panel Login Info"],
            ["1. Setup from foxnext.net", "2. Language + Basic", "3. Central", "4. Connect SSH", "5. Full Deploy", "6. Panel Login Info"],
            ["1. Setup с foxnext.net", "2. Язык + Basic", "3. Central", "4. Connect SSH", "5. Full Deploy", "6. Panel Login Info"],
            ["1. 从 foxnext.net 安装", "2. 语言 + Basic", "3. Central", "4. Connect SSH", "5. Full Deploy", "6. Panel Login Info"]),
    errors=L(["رد شدن از SSH", "تلاش Exit بدون لایسنس"], ["Skipping SSH", "Exit without license"],
             ["Пропуск SSH", "Exit без лицензии"], ["跳过SSH", "无License就加Exit"]),
    solutions=L(["ترتیب را رعایت کنید", "Registration برای Exit"], ["Follow order", "Registration before Exit"],
                ["Соблюдайте порядок", "Registration перед Exit"], ["按顺序", "Exit前先Registration"]),
    related=["setup_central", "connect_ssh", "full_deploy", "activate_license", "buy_vps"],
    clarifying=L(["نصب را تمام کرده‌اید؟", "VPS آماده دارید؟"],
                 ["Have you finished installing the app?", "Do you already have a VPS?"],
                 ["Установка приложения завершена?", "VPS уже есть?"],
                 ["应用安装好了吗？", "已经有 VPS 了吗？"]),
    faq_refs=["Q159", "Q199"],
)

add(
    intent_id="setup_central", category="Deploy", priority="critical",
    description=L("Central Server Setup", "Central Server Setup", "Central Server Setup", "Central Server Setup"),
    keywords=L(["central", "سرور مرکزی", "setup", "ssh host"], ["central", "setup central", "initial server"],
               ["central", "настройка", "сервер"], ["central", "中心服务器", "setup"]),
    sample_questions=qs(
        ["Central چطور ست کنم؟", "سرور مرکزی کجاست؟", "IP و پورت؟", "root لازم؟", "کلید یا رمز؟",
         "کشور؟", "Host قفل بعد ذخیره؟", "draft saved؟", "بدون SSH؟", "اولین دکمه؟",
         "پورت ۲۲؟", "PEM چطور؟", "یوزر غیر root؟", "اشتباه IP؟", "VPS خاموش؟",
         "Basic کشور؟", "Pro کشور آزادتر؟", "ذخیره شد؟", "بعدش Connect؟", "فرم ناقص؟"],
        ["How setup central?", "Where central button?", "IP and port?", "Need root?", "Key or password?",
         "Country field?", "Host locked after save?", "draft saved?", "Without SSH?", "First button?",
         "Port 22?", "How PEM?", "Non-root user?", "Wrong IP?", "VPS offline?",
         "Basic country?", "Pro freer country?", "Saved?", "Then Connect?", "Incomplete form?"],
        ["Как настроить Central?", "Где кнопка?", "IP и порт?", "Нужен root?", "Ключ или пароль?",
         "Страна?", "Host после сохранения?", "draft saved?", "Без SSH?", "Первая кнопка?",
         "Порт 22?", "Как PEM?", "Не root?", "Неверный IP?", "VPS выключен?",
         "Страна Basic?", "Pro свободнее?", "Сохранено?", "Потом Connect?", "Неполная форма?"],
        ["如何设置Central？", "Central按钮在哪？", "IP和端口？", "需要root吗？", "密钥还是密码？",
         "国家字段？", "保存后Host锁定？", "draft saved？", "没有SSH？", "第一个按钮？",
         "端口22？", "PEM怎么贴？", "非root？", "IP错了？", "VPS关机？",
         "Basic国家？", "Pro更自由？", "已保存？", "然后Connect？", "表单不完整？"],
    ),
    short=L("Operations → Central Server Setup: IP، پورت، کاربر، رمز یا کلید را Save کنید.",
            "Operations → Central Server Setup: save IP, port, user, password or key.",
            "Operations → Central Server Setup: сохраните IP, порт, пользователя, пароль или ключ.",
            "Operations → Central Server Setup：保存 IP、端口、用户、密码或密钥。"),
    full=L("در Basic کشور Central معمولاً IR/CN/RU. بعد از Save، Connect SSH را بزنید. Host/IP ممکن است بعداً قفل ذخیره داشته باشد.",
           "In Basic, central country is typically IR/CN/RU. After Save, run Connect SSH. Host/IP may lock after save.",
           "В Basic страна Central обычно IR/CN/RU. После Save — Connect SSH. Host/IP может блокироваться после сохранения.",
           "Basic 下 Central 国家通常为 IR/CN/RU。保存后执行 Connect SSH。Host/IP 保存后可能锁定。"),
    expert=L("ترجیح Ubuntu/Debian با root. کلید PEM کامل با BEGIN/END.",
             "Prefer Ubuntu/Debian with root. Full PEM including BEGIN/END.",
             "Предпочтительны Ubuntu/Debian и root. Полный PEM с BEGIN/END.",
             "建议 Ubuntu/Debian + root。PEM 需含完整 BEGIN/END。"),
    steps=L(["۱. Operations → Central Server Setup", "۲. فیلدها را پر کنید", "۳. Save", "۴. Connect SSH"],
            ["1. Operations → Central Server Setup", "2. Fill fields", "3. Save", "4. Connect SSH"],
            ["1. Operations → Central Server Setup", "2. Заполните поля", "3. Save", "4. Connect SSH"],
            ["1. Operations → Central Server Setup", "2. 填写字段", "3. Save", "4. Connect SSH"]),
    errors=L(["configure central first", "کشور رد شد", "فیلد خالی"],
             ["configure central first", "country rejected", "empty fields"],
             ["configure central first", "страна отклонена", "пустые поля"],
             ["configure central first", "国家被拒", "字段为空"]),
    solutions=L(["فرم را کامل کنید", "کشور مجاز Basic", "Connect SSH"],
                ["Complete form", "Allowed Basic country", "Connect SSH"],
                ["Заполните форму", "Допустимая страна Basic", "Connect SSH"],
                ["填完表单", "Basic 允许的国家", "Connect SSH"]),
    related=["connect_ssh", "full_deploy", "mode_basic", "ssh_auth_failed"],
    clarifying=L(["VPS روشن است؟", "رمز می‌گذارید یا کلید؟"],
                 ["Is the VPS powered on?", "Using password or key?"],
                 ["VPS включён?", "Пароль или ключ?"],
                 ["VPS 开机了吗？", "用密码还是密钥？"]),
    faq_refs=["Q052", "Q012", "Q018"],
)

add(
    intent_id="connect_ssh", category="Deploy", priority="critical",
    description=L("Connect SSH", "Connect SSH", "Connect SSH", "Connect SSH"),
    keywords=L(["connect ssh", "اتصال ssh", "لاگین سرور"], ["connect ssh", "ssh login", "ssh failed"],
               ["connect ssh", "ssh", "подключен"], ["connect ssh", "ssh", "连接"]),
    sample_questions=qs(
        ["Connect SSH چیه؟", "SSH وصل نمیشه", "authentication failed", "timeout", "host key",
         "رمز اشتباه؟", "کلید خراب؟", "پورت؟", "Proxy برای SSH؟", "قبل Deploy؟",
         "probe unexpected؟", "password expired؟", "چند بار؟", "وضعیت OK؟", "ترمینال خطا؟",
         "فایروال؟", "IP عوض شده؟", "root؟", "PEM؟", "چرا قطع؟"],
        ["What is Connect SSH?", "SSH won't connect", "authentication failed", "timeout", "host key",
         "Wrong password?", "Bad key?", "Port?", "Proxy for SSH?", "Before Deploy?",
         "probe unexpected?", "password expired?", "Retry?", "Status OK?", "Terminal error?",
         "Firewall?", "IP changed?", "root?", "PEM?", "Why disconnect?"],
        ["Что такое Connect SSH?", "SSH не подключается", "authentication failed", "timeout", "host key",
         "Неверный пароль?", "Плохой ключ?", "Порт?", "Proxy для SSH?", "До Deploy?",
         "probe unexpected?", "password expired?", "Повторить?", "Статус OK?", "Ошибка в terminal?",
         "Файрвол?", "IP сменился?", "root?", "PEM?", "Почему обрыв?"],
        ["什么是Connect SSH？", "SSH连不上", "authentication failed", "timeout", "host key",
         "密码错？", "密钥坏？", "端口？", "SSH要Proxy吗？", "Deploy之前？",
         "probe unexpected？", "password expired？", "重试？", "状态OK？", "终端报错？",
         "防火墙？", "IP变了？", "root？", "PEM？", "为何断开？"],
    ),
    short=L("Connect SSH ورود به Central را تست می‌کند؛ قبل از Full Deploy ضروری و در Basic رایگان است.",
            "Connect SSH tests central login; required before Full Deploy; free in Basic.",
            "Connect SSH проверяет вход на Central; нужен до Full Deploy; в Basic бесплатно.",
            "Connect SSH 测试 Central 登录；Full Deploy 前必需；Basic 免费。"),
    full=L("خطاهای رایج: authentication failed، timeout، host key changed، password expired، probe unexpected. اول credential/پورت/روشن بودن VPS و سپس Proxy.",
           "Common errors: authentication failed, timeout, host key changed, password expired, probe unexpected. Check creds/port/power then Proxy.",
           "Частые ошибки: authentication failed, timeout, host key changed, password expired, probe unexpected. Сначала credentials/порт/питание, затем Proxy.",
           "常见错误：authentication failed、timeout、host key changed、password expired、probe unexpected。先查凭证/端口/开机，再试 Proxy。"),
    expert=L("Host key را فقط اگر VPS را خودتان rebuild کرده‌اید Accept کنید.",
             "Accept host key only if you rebuilt the VPS yourself.",
             "Принимайте host key только если сами пересобрали VPS.",
             "仅在您自己重建过 VPS 时才接受 host key。"),
    steps=L(["۱. Central را Save کنید", "۲. Connect SSH", "۳. خطای ترمینال را بخوانید", "۴. در صورت فیلتر Proxy", "۵. بعد Full Deploy"],
            ["1. Save Central", "2. Connect SSH", "3. Read terminal", "4. Proxy if filtered", "5. Then Full Deploy"],
            ["1. Save Central", "2. Connect SSH", "3. Читайте terminal", "4. Proxy при фильтрации", "5. Затем Full Deploy"],
            ["1. 保存 Central", "2. Connect SSH", "3. 看终端", "4. 若被过滤开 Proxy", "5. 再 Full Deploy"]),
    errors=L(["SSH authentication failed", "SSH timeout", "host key mismatch", "password expired"],
             ["SSH authentication failed", "SSH timeout", "host key mismatch", "password expired"],
             ["SSH authentication failed", "SSH timeout", "host key mismatch", "password expired"],
             ["SSH authentication failed", "SSH timeout", "host key mismatch", "password expired"]),
    solutions=L(["رمز/PEM درست", "IP/پورت", "Proxy", "Accept host key با احتیاط", "Change password dialog"],
                ["Fix password/PEM", "IP/port", "Proxy", "Careful host key accept", "Change password dialog"],
                ["Исправьте пароль/PEM", "IP/порт", "Proxy", "Осторожно принять host key", "Смена пароля"],
                ["修正密码/PEM", "IP/端口", "Proxy", "谨慎接受 host key", "改密对话框"]),
    related=["ssh_auth_failed", "ssh_timeout", "ssh_host_key", "proxy_settings", "full_deploy"],
    clarifying=L(["متن دقیق خطا در ترمینال چیست؟", "رمز است یا کلید؟"],
                 ["Exact terminal error text?", "Password or key auth?"],
                 ["Точный текст ошибки в terminal?", "Пароль или ключ?"],
                 ["终端确切错误原文？", "密码还是密钥？"]),
    faq_refs=["Q017", "Q087", "Q088", "Q090"],
)

add(
    intent_id="full_deploy", category="Deploy", priority="critical",
    description=L("Full Deploy", "Full Deploy", "Full Deploy", "Full Deploy"),
    keywords=L(["full deploy", "دیپلوی", "نصب پنل", "wireguard"],
               ["full deploy", "install panel", "wireguard", "3x-ui"],
               ["full deploy", "установ", "панель", "wireguard"],
               ["full deploy", "部署", "面板", "wireguard"]),
    sample_questions=qs(
        ["Full Deploy چیه؟", "چطور پنل نصب کنم؟", "منبع 3X-UI؟", "GitHub یا Hub؟", "Local PC؟",
         "گیر کرده؟", "شکست خورد؟", "بدون Exit؟", "بعدش چی؟", "Panel Login؟",
         "رایگان Basic؟", "Stop زدم؟", "دیسک پر؟", "OS ساپورت؟", "جداگانه WG؟",
         "جداگانه 3X-UI؟", "لاگ کجا؟", "طولانیه؟", "AI هم میتونه؟", "قبلش SSH؟"],
        ["What is Full Deploy?", "How install panel?", "3X-UI source?", "GitHub or Hub?", "Local PC?",
         "Stuck?", "Failed?", "Without exit?", "What's next?", "Panel Login?",
         "Free in Basic?", "I hit Stop?", "Disk full?", "OS supported?", "Separate WG?",
         "Separate 3X-UI?", "Where logs?", "How long?", "AI can run it?", "SSH first?"],
        ["Что такое Full Deploy?", "Как поставить панель?", "Источник 3X-UI?", "GitHub или Hub?", "Local PC?",
         "Зависло?", "Ошибка?", "Без Exit?", "Что дальше?", "Panel Login?",
         "Бесплатно в Basic?", "Нажал Stop?", "Диск полный?", "ОС поддерживается?", "Отдельно WG?",
         "Отдельно 3X-UI?", "Где логи?", "Как долго?", "AI может?", "Сначала SSH?"],
        ["什么是Full Deploy？", "如何安装面板？", "3X-UI来源？", "GitHub还是Hub？", "Local PC？",
         "卡住？", "失败？", "没有Exit？", "接下来？", "Panel Login？",
         "Basic免费吗？", "点了Stop？", "磁盘满？", "系统支持吗？", "单独WG？",
         "单独3X-UI？", "日志在哪？", "要多久？", "AI能跑吗？", "先SSH？"],
    ),
    short=L("Full Deploy یک‌مرحله WireGuard + پنل 3X-UI را روی Central نصب می‌کند (رایگان در Basic).",
            "Full Deploy one-step installs WireGuard + 3X-UI panel on Central (free in Basic).",
            "Full Deploy за один шаг ставит WireGuard + панель 3X-UI на Central (бесплатно в Basic).",
            "Full Deploy 在 Central 上一键安装 WireGuard + 3X-UI 面板（Basic 免费）。"),
    full=L("منابع: Sanaei GitHub / BlackFox Hub / Local PC. به Exit نیاز ندارد. بعد از موفقیت Panel Login Info را باز کنید. Configure Panel جایگزین Full Deploy نیست.",
           "Sources: Sanaei GitHub / BlackFox Hub / Local PC. No exit required. After success open Panel Login Info. Configure Panel is not a substitute.",
           "Источники: Sanaei GitHub / BlackFox Hub / Local PC. Exit не нужен. После успеха — Panel Login Info. Configure Panel не замена.",
           "来源：Sanaei GitHub / BlackFox Hub / Local PC。不需要 Exit。成功后打开 Panel Login Info。Configure Panel 不能替代。"),
    expert=L("اگر GitHub فیلتر است Hub/Local. اگر ناقص ماند، Install WireGuard / Install 3X-UI جدا یا Diagnose.",
             "If GitHub filtered use Hub/Local. If partial, try separate Install WG/3X-UI or Diagnose.",
             "Если GitHub фильтруется — Hub/Local. При частичном сбое — отдельные Install или Diagnose.",
             "若 GitHub 被过滤用 Hub/Local。若部分失败，可单独 Install 或 Diagnose。"),
    steps=L(["۱. Connect SSH OK", "۲. Full Deploy", "۳. منبع را انتخاب", "۴. صبر تا پایان", "۵. Panel Login Info"],
            ["1. Connect SSH OK", "2. Full Deploy", "3. Choose source", "4. Wait", "5. Panel Login Info"],
            ["1. Connect SSH OK", "2. Full Deploy", "3. Выберите источник", "4. Дождитесь", "5. Panel Login Info"],
            ["1. Connect SSH OK", "2. Full Deploy", "3. 选择来源", "4. 等待完成", "5. Panel Login Info"]),
    errors=L(["process stopped with error", "network on VPS", "unsupported OS"],
             ["process stopped with error", "network on VPS", "unsupported OS"],
             ["process stopped with error", "network on VPS", "unsupported OS"],
             ["process stopped with error", "network on VPS", "unsupported OS"]),
    solutions=L(["منبع دیگر", "دیسک/OS", "Diagnostic Center", "تکرار بعد SSH"],
                ["Other source", "Disk/OS", "Diagnostic Center", "Retry after SSH"],
                ["Другой источник", "Диск/ОС", "Diagnostic Center", "Повтор после SSH"],
                ["换来源", "磁盘/系统", "Diagnostic Center", "SSH 后再试"]),
    related=["connect_ssh", "panel_login_info", "configure_panel", "full_deploy_failed", "panel_unreachable"],
    clarifying=L(["Connect SSH موفق بوده؟", "کدام منبع 3X-UI را زدید؟"],
                 ["Was Connect SSH successful?", "Which 3X-UI source did you pick?"],
                 ["Connect SSH успешен?", "Какой источник 3X-UI выбрали?"],
                 ["Connect SSH 成功了吗？", "选了哪个 3X-UI 来源？"]),
    faq_refs=["Q015", "Q016", "Q164"],
)

add(
    intent_id="configure_panel", category="Deploy", priority="high",
    description=L("Configure Panel", "Configure Panel", "Configure Panel", "Configure Panel"),
    keywords=L(["configure panel", "پیکربندی پنل", "outbound", "inbound"],
               ["configure panel", "inbound", "outbound", "socks"],
               ["configure panel", "inbound", "outbound", "socks"],
               ["configure panel", "inbound", "outbound", "socks"]),
    sample_questions=qs(
        ["Configure Panel چیه؟", "فرق با Full Deploy؟", "کی بزنم؟", "بدون Exit؟", "برای Node؟",
         "routing خراب؟", "SOCKS؟", "لایسنس میخواد؟", "بعد Exit؟", "ارور؟",
         "inbound؟", "outbound؟", "جای نصب پنل؟", "تعمیر؟", "چند بار؟",
         "AI هم داره؟", "Panel Login فرق؟", "تست بعدش؟", "پورت؟", "چرا لازم؟"],
        ["What is Configure Panel?", "Vs Full Deploy?", "When to run?", "Without exit?", "For node?",
         "Broken routing?", "SOCKS?", "Needs license?", "After exit?", "Errors?",
         "inbound?", "outbound?", "Install panel?", "Repair?", "Run twice?",
         "AI task?", "Vs Panel Login?", "Test after?", "Ports?", "Why needed?"],
        ["Что такое Configure Panel?", "Vs Full Deploy?", "Когда запускать?", "Без Exit?", "Для Node?",
         "Сломан routing?", "SOCKS?", "Нужна лицензия?", "После Exit?", "Ошибки?",
         "inbound?", "outbound?", "Это установка панели?", "Ремонт?", "Дважды?",
         "AI task?", "Vs Panel Login?", "Тест после?", "Порты?", "Зачем?"],
        ["什么是Configure Panel？", "和Full Deploy区别？", "何时运行？", "没有Exit？", "用于Node？",
         "路由坏了？", "SOCKS？", "要License吗？", "加Exit后？", "报错？",
         "inbound？", "outbound？", "是装面板吗？", "修复？", "跑两次？",
         "AI任务？", "和Panel Login区别？", "之后测试？", "端口？", "为什么需要？"],
    ),
    short=L("Configure Panel مسیریابی Exit/Node موجود را تعمیر می‌کند؛ نصب پنل Central نیست.",
            "Configure Panel repairs routing for an existing exit/node — not central panel install.",
            "Configure Panel чинит routing существующего Exit/Node — не установка панели на Central.",
            "Configure Panel 修复已有 Exit/Node 的路由——不是在 Central 安装面板。"),
    full=L("بعد از افزودن Exit/Node استفاده کنید. نیاز به لایسنس دارد. برای نصب اولیه Central از Full Deploy استفاده کنید.",
           "Use after adding Exit/Node. Requires license. For initial central install use Full Deploy.",
           "После добавления Exit/Node. Нужна лицензия. Для первичной установки Central — Full Deploy.",
           "在添加 Exit/Node 之后使用。需要 License。Central 首次安装请用 Full Deploy。"),
    expert=L("با Test Client و Link Test تکمیل شود. اگر credentials پنل نیست، اول Full Deploy/Panel Info.",
             "Follow with Test Client / Link Test. If panel credentials missing, Full Deploy/Panel Info first.",
             "Дополняйте Test Client / Link Test. Если нет credentials панели — сначала Full Deploy/Panel Info.",
             "随后做 Test Client / Link Test。若无面板凭据，先 Full Deploy/Panel Info。"),
    steps=L(["۱. Exit یا Node موجود باشد", "۲. Configure Panel", "۳. Test Client", "۴. در صورت نیاز Mesh/Link Test"],
            ["1. Have exit/node", "2. Configure Panel", "3. Test Client", "4. Mesh/Link Test if needed"],
            ["1. Есть Exit/Node", "2. Configure Panel", "3. Test Client", "4. При необходимости Mesh/Link Test"],
            ["1. 已有 Exit/Node", "2. Configure Panel", "3. Test Client", "4. 需要时 Mesh/Link Test"]),
    errors=L(["no exit/node", "need activate", "central panel credentials not found"],
             ["no exit/node", "need activate", "central panel credentials not found"],
             ["no exit/node", "need activate", "central panel credentials not found"],
             ["no exit/node", "need activate", "central panel credentials not found"]),
    solutions=L(["اول Exit/Node", "Registration", "Full Deploy"], ["Add exit/node first", "Registration", "Full Deploy"],
                ["Сначала Exit/Node", "Registration", "Full Deploy"], ["先有Exit/Node", "Registration", "Full Deploy"]),
    related=["full_deploy", "add_exit", "add_node", "test_client", "activate_license"],
    clarifying=L(["Exit/Node دارید؟", "مشکل نصب پنل است یا routing؟"],
                 ["Do you already have an Exit/Node?", "Is the issue panel install or routing?"],
                 ["Уже есть Exit/Node?", "Проблема в установке панели или в routing?"],
                 ["是否已有 Exit/Node？", "问题是装面板还是路由？"]),
    faq_refs=["Q020", "Q162", "Q025"],
)

add(
    intent_id="panel_login_info", category="Deploy", priority="high",
    description=L("Panel Login Info", "Panel Login Info", "Panel Login Info", "Panel Login Info"),
    keywords=L(["panel login", "یوزر پنل", "پسورد پنل", "url پنل"],
               ["panel login", "panel url", "panel password", "credentials"],
               ["panel login", "url панели", "пароль панели"],
               ["panel login", "面板地址", "面板密码"]),
    sample_questions=qs(
        ["رمز پنل کجاست؟", "Panel Login Info؟", "URL پنل؟", "پورت؟", "path؟",
         "بعد Deploy؟", "فراموش کردم؟", "در مرورگر باز نمیشه؟", "کاربر پیش‌فرض؟", "عوض کردم sync؟",
         "همه حالت‌ها یکیه؟", "کپی؟", "نداره؟", "Full Deploy اول؟", "Proxy برای باز کردن؟",
         "Add Node میگه stale؟", "refresh؟", "اندروید؟", "AI نشون میده؟", "امن نگه دارم؟"],
        ["Where panel password?", "Panel Login Info?", "Panel URL?", "Port?", "path?",
         "After Deploy?", "Forgot?", "Browser won't open?", "Default user?", "Changed sync?",
         "Same all modes?", "Copy?", "Missing?", "Full Deploy first?", "Proxy to open?",
         "Add Node stale?", "refresh?", "Android?", "AI shows it?", "Keep safe?"],
        ["Где пароль панели?", "Panel Login Info?", "URL панели?", "Порт?", "path?",
         "После Deploy?", "Забыл?", "Браузер не открывает?", "Юзер по умолчанию?", "Синк после смены?",
         "Одинаково во всех режимах?", "Копировать?", "Нет данных?", "Сначала Full Deploy?", "Proxy?",
         "Add Node stale?", "refresh?", "Android?", "AI показывает?", "Хранить безопасно?"],
        ["面板密码在哪？", "Panel Login Info？", "面板URL？", "端口？", "path？",
         "Deploy之后？", "忘了？", "浏览器打不开？", "默认用户？", "改后会同步吗？",
         "各模式相同？", "如何复制？", "没有？", "要先Full Deploy？", "打开要Proxy？",
         "Add Node说stale？", "refresh？", "Android？", "AI会显示？", "如何保管？"],
    ),
    short=L("Panel Login Info آدرس/کاربر/رمز پنل ذخیره‌شده را نشان می‌دهد (بعد از Full Deploy).",
            "Panel Login Info shows saved panel URL/user/password (after Full Deploy).",
            "Panel Login Info показывает URL/логин/пароль панели (после Full Deploy).",
            "Panel Login Info 显示已保存的面板 URL/用户/密码（Full Deploy 之后）。"),
    full=L("Store مشترک بین حالت‌هاست. اگر خالی است Full Deploy را کامل کنید. برای مرورگر فیلترشده Proxy Settings را امتحان کنید.",
           "Shared across modes. If empty, complete Full Deploy. Try Proxy Settings for filtered browsers.",
           "Общий store между режимами. Если пусто — завершите Full Deploy. Для фильтрованного доступа — Proxy Settings.",
           "各模式共享。若为空请完成 Full Deploy。浏览器受限时尝试 Proxy Settings。"),
    expert=L("تغییر credential روی سرور باید به Store همگام شود تا Add Node/API نشکند.",
             "Server-side credential changes must sync to local store or Add Node/API breaks.",
             "Смена credentials на сервере должна синхронизироваться в store, иначе ломается Add Node/API.",
             "服务器上更改凭据须同步到本地 Store，否则 Add Node/API 会失败。"),
    steps=L(["۱. Full Deploy موفق", "۲. Panel Login Info", "۳. URL کامل را کپی", "۴. در مرورگر تست"],
            ["1. Successful Full Deploy", "2. Panel Login Info", "3. Copy full URL", "4. Test in browser"],
            ["1. Успешный Full Deploy", "2. Panel Login Info", "3. Скопируйте полный URL", "4. Проверьте в браузере"],
            ["1. Full Deploy 成功", "2. Panel Login Info", "3. 复制完整 URL", "4. 浏览器测试"]),
    errors=L(["credentials not found", "panel not reachable"],
             ["credentials not found", "panel not reachable"],
             ["credentials not found", "panel not reachable"],
             ["credentials not found", "panel not reachable"]),
    solutions=L(["Full Deploy", "Proxy", "بررسی پورت/path"], ["Full Deploy", "Proxy", "Check port/path"],
                ["Full Deploy", "Proxy", "Проверьте порт/path"], ["Full Deploy", "Proxy", "检查端口/path"]),
    related=["full_deploy", "panel_unreachable", "proxy_settings", "add_node"],
    clarifying=L(["Full Deploy تمام شده؟", "مرورگر خطا می‌دهد یا برنامه؟"],
                 ["Did Full Deploy finish?", "Is the failure in browser or in-app?"],
                 ["Full Deploy завершён?", "Ошибка в браузере или в приложении?"],
                 ["Full Deploy 完成了吗？", "是浏览器失败还是应用内失败？"]),
    faq_refs=["Q019", "Q169", "Q086"],
)

# Errors & ambiguity
add(
    intent_id="ssh_auth_failed", category="Errors", priority="critical",
    description=L("خطای احراز هویت SSH", "SSH authentication failed", "Ошибка SSH authentication", "SSH 认证失败"),
    keywords=L(["authentication failed", "رمز اشتباه", "کلید نامعتبر", "ssh auth"],
               ["authentication failed", "invalid ssh", "wrong password", "bad key"],
               ["authentication failed", "неверный пароль", "ключ"],
               ["authentication failed", "密码错误", "密钥无效"]),
    sample_questions=qs(
        ["SSH authentication failed", "رمز و کلید هر دو رد شد", "Invalid SSH key and password", "چرا سیو نمیشه؟",
         "PEM خراب؟", "یوزر اشتباه؟", "منقضی شده؟", "چه کنم؟", "root؟", "پورت؟",
         "دوباره بزنم؟", "از پنل فروشنده ریست؟", "کلید کامل؟", "BEGIN END؟", "فاصله اضافه؟",
         "sudo user؟", "خطای ذخیره credential؟", "Connect جدا؟", "Deploy همون خطا؟", "کمک فوری"],
        ["SSH authentication failed", "Invalid SSH key and password", "Both key and password bad", "Why not saved?",
         "Bad PEM?", "Wrong user?", "Expired?", "What to do?", "root?", "port?",
         "Retry?", "Reset at provider?", "Full key?", "BEGIN END?", "Extra spaces?",
         "sudo user?", "Creds not saved?", "Connect alone?", "Deploy same error?", "Urgent help"],
        ["SSH authentication failed", "Invalid SSH key and password", "И ключ и пароль неверны", "Почему не сохранилось?",
         "Плохой PEM?", "Неверный user?", "Истёк?", "Что делать?", "root?", "порт?",
         "Повторить?", "Сброс у провайдера?", "Полный ключ?", "BEGIN END?", "Лишние пробелы?",
         "sudo user?", "Credentials не сохранились?", "Только Connect?", "Та же ошибка в Deploy?", "Срочно"],
        ["SSH authentication failed", "Invalid SSH key and password", "密钥和密码都无效", "为何没保存？",
         "PEM坏了？", "用户错？", "过期？", "怎么办？", "root？", "端口？",
         "重试？", "在商家面板重置？", "完整密钥？", "BEGIN END？", "多余空格？",
         "sudo用户？", "凭据未保存？", "单独Connect？", "Deploy同样错？", "紧急帮助"],
    ),
    short=L("رمز یا کلید SSH نامعتبر/منقضی است؛ credential غلط ذخیره نمی‌شود.",
            "SSH password or key is invalid/expired; bad credentials are not saved.",
            "Пароль или ключ SSH неверны/истекли; неверные credentials не сохраняются.",
            "SSH 密码或密钥无效/过期；错误凭据不会被保存。"),
    full=L("رمز را از پنل فروشنده ریست کنید، PEM کامل بچسبانید، user/port را چک کنید، اول Connect SSH. اگر password expired، دیالوگ تغییر رمز را کامل کنید.",
           "Reset password in provider panel, paste full PEM, check user/port, Connect SSH first. If password expired, complete change-password dialog.",
           "Сбросьте пароль у провайдера, вставьте полный PEM, проверьте user/port, сначала Connect SSH. При password expired — смена пароля в диалоге.",
           "在商家面板重置密码，粘贴完整 PEM，检查 user/端口，先 Connect SSH。若 password expired，完成改密对话框。"),
    expert=L("کلید و رمز هر دو fail یعنی هیچ‌کدام پذیرفته نشده؛ یکی را درست کنید نه هر دو را همزمان خراب.",
             "Both failing means neither accepted; fix one valid method.",
             "Падение и ключа и пароля значит не принят ни один способ; исправьте один валидный.",
             "密钥与密码都失败表示都未被接受；修好一种有效方式即可。"),
    steps=L(["۱. ریست رمز در پنل VPS", "۲. PEM کامل", "۳. user/port", "۴. Connect SSH", "۵. بعد Deploy"],
            ["1. Reset VPS password", "2. Full PEM", "3. user/port", "4. Connect SSH", "5. Then Deploy"],
            ["1. Сброс пароля VPS", "2. Полный PEM", "3. user/port", "4. Connect SSH", "5. Затем Deploy"],
            ["1. 重置 VPS 密码", "2. 完整 PEM", "3. user/端口", "4. Connect SSH", "5. 再 Deploy"]),
    errors=L(["Invalid SSH key and password", "password expired"],
             ["Invalid SSH key and password", "password expired"],
             ["Invalid SSH key and password", "password expired"],
             ["Invalid SSH key and password", "password expired"]),
    solutions=L(["ریست رمز", "PEM درست", "Change password dialog"],
                ["Reset password", "Fix PEM", "Change password dialog"],
                ["Сброс пароля", "Исправить PEM", "Диалог смены пароля"],
                ["重置密码", "修正 PEM", "改密对话框"]),
    related=["connect_ssh", "setup_central", "ssh_timeout"],
    clarifying=L(["از رمز استفاده می‌کنید یا کلید؟", "متن دقیق دیالوگ چیست؟"],
                 ["Using password or key?", "Exact dialog text?"],
                 ["Пароль или ключ?", "Точный текст диалога?"],
                 ["用密码还是密钥？", "对话框确切原文？"]),
    faq_refs=["Q088", "Q089"],
)

add(
    intent_id="ssh_timeout", category="Errors", priority="high",
    description=L("SSH timeout", "SSH timeout", "SSH timeout", "SSH timeout"),
    keywords=L(["timeout", "تایم اوت", "وصل نمیشه", "فیلتر"],
               ["timeout", "unreachable", "firewall", "filtered"],
               ["timeout", "недоступен", "файрвол"],
               ["timeout", "连不上", "防火墙", "过滤"]),
    sample_questions=qs(
        ["SSH timeout", "سرور جواب نمیده", "پورت بسته؟", "VPS خاموش؟", "IP اشتباه؟",
         "فیلتر ایران؟", "Proxy Settings؟", "ISP؟", "فایروال ابری؟", "پورت غیر۲۲؟",
         "Diagnostic؟", "چند بار تست؟", "پینگ؟", "بعد از تعویض IP؟", "Deploy timeout؟",
         "فقط از خونه؟", "VPN سیستم؟", "Auto proxy؟", "Iran profile؟", "کمک"],
        ["SSH timeout", "Server not answering", "Port closed?", "VPS off?", "Wrong IP?",
         "Iran filter?", "Proxy Settings?", "ISP?", "Cloud firewall?", "Non-22 port?",
         "Diagnostic?", "Retry?", "Ping?", "After IP change?", "Deploy timeout?",
         "Only from home?", "System VPN?", "Auto proxy?", "Iran profile?", "Help"],
        ["SSH timeout", "Сервер не отвечает", "Порт закрыт?", "VPS выключен?", "Неверный IP?",
         "Фильтр?", "Proxy Settings?", "ISP?", "Cloud firewall?", "Не 22 порт?",
         "Diagnostic?", "Повтор?", "Ping?", "После смены IP?", "Deploy timeout?",
         "Только из дома?", "Системный VPN?", "Auto proxy?", "Iran profile?", "Помощь"],
        ["SSH timeout", "服务器无响应", "端口关闭？", "VPS关机？", "IP错误？",
         "被过滤？", "Proxy Settings？", "ISP？", "云防火墙？", "非22端口？",
         "Diagnostic？", "重试？", "Ping？", "换IP后？", "Deploy超时？",
         "仅家里不行？", "系统VPN？", "Auto proxy？", "Iran profile？", "求助"],
    ),
    short=L("میزبان در مهلت پاسخ نداد؛ IP/پورت/روشن بودن/فایروال یا Proxy را چک کنید.",
            "Host did not answer in time; check IP/port/power/firewall or Proxy.",
            "Хост не ответил вовремя; проверьте IP/порт/питание/файрвол или Proxy.",
            "主机超时无响应；检查 IP/端口/开机/防火墙或 Proxy。"),
    full=L("Proxy Settings با پروفایل Auto/Iran/Free را امتحان کنید. پورت SSH را از پنل فروشنده تأیید کنید.",
           "Try Proxy Settings Auto/Iran/Free profiles. Confirm SSH port in provider panel.",
           "Попробуйте Proxy Settings Auto/Iran/Free. Подтвердите SSH-порт у провайдера.",
           "尝试 Proxy Settings 的 Auto/Iran/Free。在商家面板确认 SSH 端口。"),
    expert=L("اگر فقط Deploy تایم‌اوت می‌کند ولی Connect لحظه‌ای OK است، پایداری شبکه/فیلتر میانی را بررسی کنید.",
             "If only long Deploy times out while Connect briefly OK, check mid-path filtering/stability.",
             "Если Connect кратко OK, а длинный Deploy падает — смотрите фильтрацию/стабильность пути.",
             "若短 Connect 正常但长 Deploy 超时，检查中间路径过滤/稳定性。"),
    steps=L(["۱. VPS روشن", "۲. IP/پورت", "۳. Proxy Settings", "۴. Connect SSH", "۵. Diagnostic Center"],
            ["1. VPS on", "2. IP/port", "3. Proxy Settings", "4. Connect SSH", "5. Diagnostic Center"],
            ["1. VPS включён", "2. IP/порт", "3. Proxy Settings", "4. Connect SSH", "5. Diagnostic Center"],
            ["1. VPS 开机", "2. IP/端口", "3. Proxy Settings", "4. Connect SSH", "5. Diagnostic Center"]),
    errors=L(["SSH timeout", "SSH failed: timeout"], ["SSH timeout", "SSH failed: timeout"],
             ["SSH timeout", "SSH failed: timeout"], ["SSH timeout", "SSH failed: timeout"]),
    solutions=L(["Proxy", "فایروال فروشنده", "IP درست"], ["Proxy", "Provider firewall", "Correct IP"],
                ["Proxy", "Файрвол провайдера", "Верный IP"], ["Proxy", "商家防火墙", "正确 IP"]),
    related=["connect_ssh", "proxy_settings", "ssh_auth_failed"],
    clarifying=L(["پینگ/پنل فروشنده باز می‌شود؟", "پورت SSH چند است؟"],
                 ["Can you open the provider panel / is VPS online?", "What SSH port?"],
                 ["VPS онлайн в панели провайдера?", "Какой SSH-порт?"],
                 ["商家面板里 VPS 在线吗？", "SSH 端口是多少？"]),
    faq_refs=["Q090", "Q030"],
)

add(
    intent_id="ssh_host_key", category="Errors", priority="medium",
    description=L("تغییر SSH host key", "SSH host key changed", "Смена SSH host key", "SSH host key 变更"),
    keywords=L(["host key", "mismatch", "کلید میزبان"], ["host key", "mismatch", "known_hosts"],
               ["host key", "mismatch"], ["host key", "mismatch", "主机密钥"]),
    sample_questions=qs(
        ["host key changed", "mismatch", "Accept کنم؟", "بعد از ری‌اینستال VPS؟", "MITM؟",
         " Cleared stored؟", "retry؟", "خطرناکه؟", "IP همونه؟", "فروشنده rebuild؟",
         "چی کار کنم؟", "رد کنم؟", "Connect دوباره؟", "چرا اومد؟", "امن؟",
         "fingerprint؟", "دیالوگ؟", "همه سرورها؟", "فقط یکی؟", "کمک"],
        ["host key changed", "mismatch", "Should I Accept?", "After VPS reinstall?", "MITM?",
         "Cleared stored?", "retry?", "Dangerous?", "Same IP?", "Provider rebuild?",
         "What to do?", "Reject?", "Connect again?", "Why?", "Safe?",
         "fingerprint?", "dialog?", "All servers?", "Only one?", "Help"],
        ["host key changed", "mismatch", "Принять Accept?", "После переустановки VPS?", "MITM?",
         "Cleared stored?", "retry?", "Опасно?", "Тот же IP?", "Rebuild у провайдера?",
         "Что делать?", "Отклонить?", "Снова Connect?", "Почему?", "Безопасно?",
         "fingerprint?", "диалог?", "Все серверы?", "Только один?", "Помощь"],
        ["host key changed", "mismatch", "该Accept吗？", "VPS重装后？", "MITM？",
         "Cleared stored？", "retry？", "危险吗？", "同一IP？", "商家rebuild？",
         "怎么办？", "拒绝？", "再Connect？", "为何出现？", "安全吗？",
         "fingerprint？", "对话框？", "所有服务器？", "仅一台？", "求助"],
    ),
    short=L("اثرانگشت SSH سرور عوض شده؛ فقط اگر خودتان VPS را rebuild کرده‌اید Accept کنید.",
            "Server SSH fingerprint changed; Accept only if you rebuilt the VPS yourself.",
            "Отпечаток SSH сервера изменился; Accept только если сами пересобрали VPS.",
            "服务器 SSH 指纹已变更；仅在您自己重建 VPS 时 Accept。"),
    full=L("بعد از Accept معمولاً کلید ذخیره‌شده پاک و اتصال retry می‌شود. اگر غیرمنتظره است، IP/مالکیت را قبل از Accept بررسی کنید.",
           "After Accept, stored key is cleared and connection retries. If unexpected, verify IP ownership before Accept.",
           "После Accept сохранённый ключ очищается и идёт retry. Если неожиданно — проверьте владение IP до Accept.",
           "Accept 后会清除已存密钥并重试。若非预期，Accept 前先核实 IP 归属。"),
    expert=L("MITM واقعی نادر است ولی در شبکه‌های خصمانه محتمل؛ بدون تأیید مالکیت Accept نکنید.",
             "Real MITM is rare but possible on hostile networks; don't Accept without ownership confirmation.",
             "Реальный MITM редок, но возможен; не Accept без подтверждения владения.",
             "真实 MITM 少见但可能；未确认归属前不要 Accept。"),
    steps=L(["۱. تأیید rebuild در پنل فروشنده", "۲. Accept فقط در صورت اعتماد", "۳. Connect SSH", "۴. اگر مشکوک توقف"],
            ["1. Confirm rebuild in provider", "2. Accept only if trusted", "3. Connect SSH", "4. Stop if suspicious"],
            ["1. Подтвердите rebuild у провайдера", "2. Accept только если доверяете", "3. Connect SSH", "4. Стоп если подозрительно"],
            ["1. 在商家面板确认 rebuild", "2. 可信才 Accept", "3. Connect SSH", "4. 可疑则停止"]),
    errors=L(["SSH Host Key Changed", "host key mismatch"],
             ["SSH Host Key Changed", "host key mismatch"],
             ["SSH Host Key Changed", "host key mismatch"],
             ["SSH Host Key Changed", "host key mismatch"]),
    solutions=L(["Accept آگاهانه", "بررسی IP"], ["Informed Accept", "Verify IP"],
                ["Осознанный Accept", "Проверка IP"], ["知情 Accept", "核实 IP"]),
    related=["connect_ssh", "setup_central"],
    clarifying=L(["VPS را تازه نصب/ری‌بیلد کرده‌اید؟", "IP همان سرور قبلی است؟"],
                 ["Did you freshly reinstall/rebuild the VPS?", "Is it the same IP as before?"],
                 ["Вы только что переустановили/пересобрали VPS?", "Тот же IP, что раньше?"],
                 ["是否刚重装/重建了 VPS？", "是否仍是原来的 IP？"]),
    faq_refs=["Q087"],
)

add(
    intent_id="full_deploy_failed", category="Errors", priority="critical",
    description=L("شکست Full Deploy", "Full Deploy failed", "Сбой Full Deploy", "Full Deploy 失败"),
    keywords=L(["deploy fail", "دیپلوی خطا", "نصب نشد", "process stopped"],
               ["deploy failed", "process stopped", "install failed", "full deploy error"],
               ["deploy ошибка", "process stopped", "установка не"],
               ["deploy失败", "process stopped", "安装失败"]),
    sample_questions=qs(
        ["Full Deploy شکست", "process stopped with an error", "نصب پنل نشد", "وسطش قطع شد", "Stop زدم",
         "دیسک پر", "apt خطا", "GitHub نمیاد", "Hub بهتره؟", "Local PC؟",
         "دوباره بزنم؟", "SSH هنوز OK؟", "لاگ ترمینال؟", "Diagnostic؟", "OS چی؟",
         "نیمه‌کاره؟", "Install جدا؟", "AI Diagnose؟", "پشتیبانی؟", "چیکار کنم؟"],
        ["Full Deploy failed", "process stopped with an error", "Panel not installed", "Interrupted", "I pressed Stop",
         "Disk full", "apt error", "GitHub blocked", "Try Hub?", "Local PC?",
         "Retry?", "SSH still OK?", "Terminal log?", "Diagnostic?", "Which OS?",
         "Partial?", "Separate install?", "AI Diagnose?", "Support?", "What now?"],
        ["Full Deploy failed", "process stopped with an error", "Панель не встала", "Прервалось", "Нажал Stop",
         "Диск полный", "ошибка apt", "GitHub недоступен", "Попробовать Hub?", "Local PC?",
         "Повторить?", "SSH ещё OK?", "Лог terminal?", "Diagnostic?", "Какая ОС?",
         "Частично?", "Отдельная установка?", "AI Diagnose?", "Поддержка?", "Что делать?"],
        ["Full Deploy失败", "process stopped with an error", "面板没装上", "中断了", "点了Stop",
         "磁盘满", "apt错误", "GitHub不通", "试Hub？", "Local PC？",
         "重试？", "SSH仍OK？", "终端日志？", "Diagnostic？", "什么系统？",
         "半成品？", "分开安装？", "AI Diagnose？", "找支持？", "现在怎么办？"],
    ),
    short=L("Full Deploy قبل از آماده‌شدن پنل/WG متوقف شده؛ ترمینال را بخوانید و منبع/SSH را درست کنید.",
            "Full Deploy stopped before panel/WG ready; read terminal and fix source/SSH.",
            "Full Deploy остановился до готовности панели/WG; читайте terminal и исправьте source/SSH.",
            "Full Deploy 在面板/WG 就绪前停止；查看终端并修正来源/SSH。"),
    full=L("Connect SSH را تأیید کنید، منبع دیگر (Hub/Local) را امتحان کنید، دیسک/OS را چک کنید، بدون بستن UI busy دوباره اجرا کنید، Diagnostic Center.",
           "Confirm Connect SSH, try another source (Hub/Local), check disk/OS, rerun without closing busy UI, Diagnostic Center.",
           "Проверьте Connect SSH, другой источник (Hub/Local), диск/ОС, повторите не закрывая busy UI, Diagnostic Center.",
           "确认 Connect SSH，换来源（Hub/Local），检查磁盘/系统，勿关闭 busy UI 重跑，Diagnostic Center。"),
    expert=L("stderr لینوکس دقیق ممکن است NEED_MORE_REVIEW باشد؛ لاگ کامل + Device ID برای پشتیبانی بفرستید.",
             "Exact Linux stderr may be NEED_MORE_REVIEW; send full log + Device ID to support.",
             "Точный Linux stderr может быть NEED_MORE_REVIEW; полный лог + Device ID в поддержку.",
             "精确 Linux stderr 可能属 NEED_MORE_REVIEW；把完整日志 + Device ID 发给支持。"),
    steps=L(["۱. Connect SSH", "۲. منبع دیگر", "۳. تکرار Full Deploy", "۴. Diagnostic", "۵. پشتیبانی در صورت نیاز"],
            ["1. Connect SSH", "2. Other source", "3. Retry Full Deploy", "4. Diagnostic", "5. Support if needed"],
            ["1. Connect SSH", "2. Другой источник", "3. Повтор Full Deploy", "4. Diagnostic", "5. Поддержка"],
            ["1. Connect SSH", "2. 换来源", "3. 重试 Full Deploy", "4. Diagnostic", "5. 必要时支持"]),
    errors=L(["process stopped with an error", "network/package failure"],
             ["process stopped with an error", "network/package failure"],
             ["process stopped with an error", "network/package failure"],
             ["process stopped with an error", "network/package failure"]),
    solutions=L(["Hub/Local", "دیسک آزاد", "OS استاندارد"], ["Hub/Local", "Free disk", "Standard OS"],
                ["Hub/Local", "Свободное место", "Стандартная ОС"], ["Hub/Local", "释放磁盘", "标准系统"]),
    related=["full_deploy", "connect_ssh", "check_system", "contact_support"],
    clarifying=L(["آخرین خطوط ترمینال چیست؟", "کدام منبع را انتخاب کردید؟"],
                 ["What are the last terminal lines?", "Which install source did you choose?"],
                 ["Какие последние строки terminal?", "Какой источник установки?"],
                 ["终端最后几行是什么？", "选了哪个安装来源？"]),
    faq_refs=["Q054"],
)

add(
    intent_id="panel_unreachable", category="Errors", priority="high",
    description=L("پنل بعد از Deploy باز نمی‌شود", "Panel unreachable after deploy", "Панель недоступна после deploy", "部署后面板打不开"),
    keywords=L(["پنل باز نمیشه", "panel not reachable", "url غلط", "credentials not found"],
               ["panel not reachable", "can't open panel", "credentials not found", "stale path"],
               ["панель не откры", "credentials not found", "недоступна"],
               ["面板打不开", "credentials not found", "无法访问"]),
    sample_questions=qs(
        ["پنل باز نمیشه", "URL اشتباه؟", "پورت؟", "path؟", "فایروال؟",
         "credentials not found", "Add Node stale", "مرورگر timeout", "Proxy؟", "سرویس down؟",
         "Panel Login خالیه؟", "Full Deploy اول؟", "CDN؟", "دامنه؟", "پسورد عوض شده؟",
         "از خارج؟", "از ایران؟", "رفرش؟", "دوباره Deploy؟", "کمک"],
        ["Panel won't open", "Wrong URL?", "Port?", "path?", "Firewall?",
         "credentials not found", "Add Node stale", "Browser timeout", "Proxy?", "Service down?",
         "Panel Login empty?", "Full Deploy first?", "CDN?", "Domain?", "Password changed?",
         "From abroad?", "From Iran?", "Refresh?", "Redeploy?", "Help"],
        ["Панель не открывается", "Неверный URL?", "Порт?", "path?", "Файрвол?",
         "credentials not found", "Add Node stale", "Таймаут браузера", "Proxy?", "Сервис down?",
         "Panel Login пуст?", "Сначала Full Deploy?", "CDN?", "Домен?", "Пароль сменён?",
         "Из-за рубежа?", "Из Ирана?", "Обновить?", "Снова Deploy?", "Помощь"],
        ["面板打不开", "URL错？", "端口？", "path？", "防火墙？",
         "credentials not found", "Add Node stale", "浏览器超时", "Proxy？", "服务挂了？",
         "Panel Login空？", "先Full Deploy？", "CDN？", "域名？", "密码改了？",
         "国外访问？", "伊朗访问？", "刷新？", "重新Deploy？", "求助"],
    ),
    short=L("URL/پورت/path یا فایروال/شبکه مانع دسترسی به پنل است؛ اول Panel Login Info را چک کنید.",
            "URL/port/path or firewall/network blocks panel access; check Panel Login Info first.",
            "URL/порт/path или файрвол/сеть мешают доступу; сначала Panel Login Info.",
            "URL/端口/path 或防火墙/网络阻止访问；先查看 Panel Login Info。"),
    full=L("کپی دقیق URL، تست مرورگر، Proxy Settings، در صورت نیاز Full Deploy مجدد یا Install 3X-UI. برای Add Node اگر stale path است Panel Info/Deploy را تازه کنید.",
           "Copy exact URL, browser test, Proxy Settings, rerun Full Deploy/Install 3X-UI if needed. For Add Node stale path, refresh Panel Info/Deploy.",
           "Скопируйте точный URL, тест браузера, Proxy Settings, при необходимости снова Full Deploy/Install 3X-UI. Для stale path — обновите Panel Info/Deploy.",
           "复制准确 URL，浏览器测试，Proxy Settings，必要时重跑 Full Deploy/Install 3X-UI。Add Node 若 stale path，刷新 Panel Info/Deploy。"),
    expert=L("همگام نبودن password/path محلی با سرور باعث شکست API نود می‌شود.",
             "Local password/path drift vs server breaks node API login.",
             "Рассинхрон локальных password/path с сервером ломает API логин ноды.",
             "本地 password/path 与服务器不一致会导致节点 API 登录失败。"),
    steps=L(["۱. Panel Login Info", "۲. مرورگر", "۳. Proxy", "۴. Full Deploy/Install در صورت نیاز", "۵. Retry Add Node"],
            ["1. Panel Login Info", "2. Browser", "3. Proxy", "4. Full Deploy/Install if needed", "5. Retry Add Node"],
            ["1. Panel Login Info", "2. Браузер", "3. Proxy", "4. Full Deploy/Install при необходимости", "5. Снова Add Node"],
            ["1. Panel Login Info", "2. 浏览器", "3. Proxy", "4. 必要时 Full Deploy/Install", "5. 重试 Add Node"]),
    errors=L(["Central panel credentials not found", "Could not log in to the central panel API"],
             ["Central panel credentials not found", "Could not log in to the central panel API"],
             ["Central panel credentials not found", "Could not log in to the central panel API"],
             ["Central panel credentials not found", "Could not log in to the central panel API"]),
    solutions=L(["Full Deploy", "Panel Info", "Proxy"], ["Full Deploy", "Panel Info", "Proxy"],
                ["Full Deploy", "Panel Info", "Proxy"], ["Full Deploy", "Panel Info", "Proxy"]),
    related=["panel_login_info", "full_deploy", "proxy_settings", "add_node"],
    clarifying=L(["Panel Login Info چیزی نشان می‌دهد؟", "خطا در مرورگر است یا داخل برنامه؟"],
                 ["Does Panel Login Info show values?", "Is the failure in browser or in-app?"],
                 ["Panel Login Info что-то показывает?", "Ошибка в браузере или в приложении?"],
                 ["Panel Login Info 有显示吗？", "是浏览器失败还是应用内？"]),
    faq_refs=["Q054", "Q086", "Q147"],
)

add(
    intent_id="need_activate", category="Errors", priority="critical",
    description=L("نیاز به فعال‌سازی", "Need activate / Limited Access", "Нужна активация / Limited Access", "需要激活 / Limited Access"),
    keywords=L(["limited access", "need activate", "فعال کنید", "قفل"],
               ["limited access", "need activate", "please activate", "locked"],
               ["limited access", "need activate", "активируйте", "заблок"],
               ["limited access", "need activate", "请激活", "锁定"]),
    sample_questions=qs(
        ["Limited Access", "Please activate via Registration", "دکمه قفله", "Exit نمیذاره", "Configure قفل",
         "چرا؟", "چیکار کنم؟", "Basic کافیه؟", "کجا فعال؟", "کد ندارم؟",
         "خرید کجا؟", "بعد Activate؟", "همچنان قفل؟", "View؟", "Refresh؟",
         "اشتباه سطح؟", "منقضی؟", "Reactivation؟", "پشتیبانی؟", "کمک"],
        ["Limited Access", "Please activate via Registration", "Button locked", "Can't add exit", "Configure locked",
         "Why?", "What now?", "Is Basic enough?", "Where activate?", "No code?",
         "Where buy?", "After Activate?", "Still locked?", "View?", "Refresh?",
         "Wrong tier?", "Expired?", "Reactivation?", "Support?", "Help"],
        ["Limited Access", "Please activate via Registration", "Кнопка заблокирована", "Нельзя Add Exit", "Configure locked",
         "Почему?", "Что делать?", "Хватит Basic?", "Где активировать?", "Нет кода?",
         "Где купить?", "После Activate?", "Всё ещё locked?", "View?", "Обновить?",
         "Неверный тариф?", "Истекла?", "Reactivation?", "Поддержка?", "Помощь"],
        ["Limited Access", "Please activate via Registration", "按钮锁定", "无法Add Exit", "Configure锁定",
         "为什么？", "怎么办？", "Basic够吗？", "哪里激活？", "没有代码？",
         "哪里买？", "Activate之后？", "仍锁定？", "View？", "刷新？",
         "层级错？", "过期？", "Reactivation？", "支持？", "求助"],
    ),
    short=L("قابلیت پولی/قفل است؛ تب Registration را برای Activate باز کنید.",
            "Feature is gated; open Registration and Activate.",
            "Функция закрыта; откройте Registration и Activate.",
            "功能被门控；打开 Registration 并 Activate。"),
    full=L("Exit/Configure و بسیاری ابزارها بدون لایسنس باز نمی‌شوند. فقط Setup Central + Connect SSH + Full Deploy در Basic رایگان‌اند.",
           "Exits/Configure and many tools need license. Only Setup Central + Connect SSH + Full Deploy are free in Basic.",
           "Exit/Configure и много инструментов требуют лицензию. В Basic бесплатны только Setup Central + Connect SSH + Full Deploy.",
           "Exit/Configure 及多数工具需 License。Basic 仅 Setup Central + Connect SSH + Full Deploy 免费。"),
    expert=L("اگر Pro feature است پیام need Pro می‌آید نه فقط Limited Access.",
             "Pro-only features show need Pro, not only Limited Access.",
             "Для Pro-only будет need Pro, не только Limited Access.",
             "仅 Pro 功能会显示 need Pro，不只是 Limited Access。"),
    steps=L(["۱. Registration", "۲. Activate سطح لازم", "۳. دکمه را دوباره بزنید"],
            ["1. Registration", "2. Activate required tier", "3. Retry the button"],
            ["1. Registration", "2. Activate нужного тарифа", "3. Повторите кнопку"],
            ["1. Registration", "2. 激活所需层级", "3. 重试按钮"]),
    errors=L(["Limited Access", "Please activate via Registration tab first"],
             ["Limited Access", "Please activate via Registration tab first"],
             ["Limited Access", "Please activate via Registration tab first"],
             ["Limited Access", "Please activate via Registration tab first"]),
    solutions=L(["Activate", "خرید از foxnext.net"], ["Activate", "Buy on foxnext.net"],
                ["Activate", "Купить на foxnext.net"], ["Activate", "在 foxnext.net 购买"]),
    related=["activate_license", "need_pro", "mode_basic", "pricing"],
    clarifying=L(["کدام دکمه قفل است؟", "پیام Limited Access است یا need Pro؟"],
                 ["Which button is locked?", "Is the message Limited Access or need Pro?"],
                 ["Какая кнопка заблокирована?", "Сообщение Limited Access или need Pro?"],
                 ["哪个按钮被锁？", "提示是 Limited Access 还是 need Pro？"]),
    faq_refs=["Q048", "Q037"],
)

add(
    intent_id="need_pro", category="Errors", priority="high",
    description=L("نیاز به Pro", "Need Pro activation", "Нужна активация Pro", "需要 Pro 激活"),
    keywords=L(["need pro", "requires pro", "پرو لازم"], ["requires pro", "need pro", "pro activation"],
               ["requires pro", "нужен pro"], ["requires pro", "需要pro"]),
    sample_questions=qs(
        ["This feature requires Pro activation", "تونل قفل", "نود قفل", "CDN قفل", "Mesh قفل",
         "Mirza قفل", "Domain قفل", "چرا Pro؟", "AI Pro کافیه؟", "Basic نه؟",
         "چطور باز کنم؟", "BFXP؟", "View Pro؟", "بعد Activate؟", "همچنان؟",
         "Move Central؟", "Factory Reset؟", "خرید؟", "فرق با Limited Access؟", "کمک"],
        ["This feature requires Pro activation", "Tunnel locked", "Node locked", "CDN locked", "Mesh locked",
         "Mirza locked", "Domain locked", "Why Pro?", "AI Pro enough?", "Not Basic?",
         "How unlock?", "BFXP?", "View Pro?", "After Activate?", "Still locked?",
         "Move Central?", "Factory Reset?", "Buy?", "Vs Limited Access?", "Help"],
        ["This feature requires Pro activation", "Туннель locked", "Node locked", "CDN locked", "Mesh locked",
         "Mirza locked", "Domain locked", "Почему Pro?", "AI Pro хватит?", "Не Basic?",
         "Как открыть?", "BFXP?", "View Pro?", "После Activate?", "Всё ещё?",
         "Move Central?", "Factory Reset?", "Купить?", "Vs Limited Access?", "Помощь"],
        ["This feature requires Pro activation", "隧道锁定", "Node锁定", "CDN锁定", "Mesh锁定",
         "Mirza锁定", "Domain锁定", "为何Pro？", "AI Pro够吗？", "Basic不行？",
         "如何解锁？", "BFXP？", "View Pro？", "Activate之后？", "仍锁定？",
         "Move Central？", "Factory Reset？", "购买？", "和Limited Access区别？", "求助"],
    ),
    short=L("این قابلیت فقط با فعال‌سازی Pro (یا AI Pro که Pro را هم می‌دهد) باز می‌شود.",
            "This feature needs Pro activation (or AI Pro, which also unlocks Pro ops).",
            "Эта функция требует активации Pro (или AI Pro, который также открывает Pro).",
            "该功能需要激活 Pro（或同时解锁 Pro 操作的 AI Pro）。"),
    full=L("پیام استاندارد: This feature requires Pro activation. Activate BFXP/BFXA، سپس View را Pro/AI Pro کنید.",
           "Standard message: This feature requires Pro activation. Activate BFXP/BFXA, then switch View to Pro/AI Pro.",
           "Стандарт: This feature requires Pro activation. Активируйте BFXP/BFXA и переключите View.",
           "标准提示：This feature requires Pro activation。激活 BFXP/BFXA，并将 View 切到 Pro/AI Pro。"),
    expert=L("Pro به‌تنهایی AI chat را باز نمی‌کند.",
             "Pro alone does not unlock AI chat.",
             "Одного Pro недостаточно для AI-чата.",
             "仅有 Pro 不能解锁 AI 聊天。"),
    steps=L(["۱. Activate Pro یا AI Pro", "۲. View → Pro/AI Pro", "۳. Retry"],
            ["1. Activate Pro or AI Pro", "2. View → Pro/AI Pro", "3. Retry"],
            ["1. Activate Pro или AI Pro", "2. View → Pro/AI Pro", "3. Retry"],
            ["1. 激活 Pro 或 AI Pro", "2. View → Pro/AI Pro", "3. 重试"]),
    errors=L(["This feature requires Pro activation"], ["This feature requires Pro activation"],
             ["This feature requires Pro activation"], ["This feature requires Pro activation"]),
    solutions=L(["BFXP/BFXA", "سوییچ View"], ["BFXP/BFXA", "Switch View"],
                ["BFXP/BFXA", "Смена View"], ["BFXP/BFXA", "切换 View"]),
    related=["mode_pro", "activate_license", "need_activate", "mode_ai_pro"],
    clarifying=L(["کدام قابلیت Pro را زدید؟", "لایسنس Pro دارید یا فقط Basic؟"],
                 ["Which Pro feature did you click?", "Do you have Pro license or only Basic?"],
                 ["Какую Pro-функцию нажали?", "Есть Pro или только Basic?"],
                 ["点了哪个 Pro 功能？", "已有 Pro 还是只有 Basic？"]),
    faq_refs=["Q049", "Q008"],
)

add(
    intent_id="ambiguous_app_broken", category="Meta", priority="critical",
    description=L("گزارش مبهم «کار نمی‌کند»", "Ambiguous 'app doesn't work'", "Неясная жалоба «не работает»", "含糊的「不能用」"),
    keywords=L(["کار نمیکنه", "خراب", "ارور", "مشکل"], ["doesn't work", "broken", "error", "problem", "not working"],
               ["не работает", "сломал", "ошибка", "проблема"], ["不能用", "坏了", "报错", "问题"]),
    sample_questions=qs(
        ["برنامه کار نمی‌کند", "کار نمیکنه", "یه مشکل دارم", "ارور میده", "خراب شد",
         "کمک", "درست نمیشه", "گیر کردم", "نمیدونم چی شده", "هیچی باز نمیشه",
         "باگ", "کریش", "هنگ", "سفید", "قفل",
         "اینترنت؟", "نصب؟", "فعال‌سازی؟", "اتصال؟", "آپدیت؟"],
        ["App doesn't work", "Broken", "I have a problem", "Shows error", "Help",
         "Stuck", "Don't know what happened", "Nothing opens", "Bug", "Crash",
         "Hang", "Blank", "Locked", "Internet?", "Install?",
         "Activation?", "Connection?", "Update?", "Please help", "Something wrong"],
        ["Программа не работает", "Сломалось", "Проблема", "Ошибка", "Помогите",
         "Застрял", "Не знаю что случилось", "Ничего не открывается", "Баг", "Крэш",
         "Зависло", "Белый экран", "Заблокировано", "Интернет?", "Установка?",
         "Активация?", "Подключение?", "Обновление?", "Помогите пожалуйста", "Что-то не так"],
        ["程序不能用", "坏了", "有问题", "报错", "救命",
         "卡住了", "不知道怎么了", "什么都打不开", "Bug", "崩溃",
         "卡死", "白屏", "锁定", "网络？", "安装？",
         "激活？", "连接？", "更新？", "请帮忙", "不对劲"],
    ),
    short=L("برای کمک دقیق باید مرحله مشکل مشخص شود.",
            "Need the failing stage to help accurately.",
            "Нужно понять этап сбоя.",
            "需要明确出问题的阶段。"),
    full=L("بدون جزئیات نباید حدس زد. از کاربر بخواهید یکی را انتخاب کند: نصب / فعال‌سازی / اتصال SSH / آپدیت / AI / دیگر.",
           "Do not guess. Ask the user to pick: install / activation / SSH connect / update / AI / other.",
           "Не угадывайте. Попросите выбрать: установка / активация / SSH / обновление / AI / другое.",
           "不要猜测。请用户选择：安装 / 激活 / SSH连接 / 更新 / AI / 其他。"),
    expert=L("بعد از انتخاب مرحله، به intent تخصصی همان دسته route کنید و Device ID+اسکرین بخواهید.",
             "After stage selection, route to the specialized intent and ask Device ID+screenshot.",
             "После выбора этапа направьте в профильный intent и попросите Device ID+скрин.",
             "选定阶段后路由到对应 intent，并索取 Device ID+截图。"),
    steps=L(["۱. بپرسید مرحله کدام است", "۲. اسکرین/متن خطا", "۳. Device ID", "۴. intent تخصصی"],
            ["1. Ask which stage", "2. Screenshot/error text", "3. Device ID", "4. Specialized intent"],
            ["1. Спросите этап", "2. Скрин/текст ошибки", "3. Device ID", "4. Профильный intent"],
            ["1. 询问阶段", "2. 截图/错误原文", "3. Device ID", "4. 专业 intent"]),
    errors=L(["گزارش مبهم"], ["Ambiguous report"], ["Неясная жалоба"], ["含糊反馈"]),
    solutions=L(["سوال شفاف‌سازی", "route به intent درست"], ["Clarifying question", "Route to right intent"],
                ["Уточняющий вопрос", "Маршрут в нужный intent"], ["澄清问题", "路由到正确 intent"]),
    related=["install_setup", "activate_license", "connect_ssh", "force_update", "mode_ai_pro", "contact_support"],
    clarifying=L([
        "لطفاً بفرمایید مشکل در کدام مرحله است؟\n1) نصب\n2) فعال‌سازی\n3) اتصال SSH / Deploy\n4) آپدیت\n5) AI\n6) دیگر",
    ], [
        "Which stage is failing?\n1) Install\n2) Activation\n3) SSH / Deploy\n4) Update\n5) AI\n6) Other",
    ], [
        "На каком этапе проблема?\n1) Установка\n2) Активация\n3) SSH / Deploy\n4) Обновление\n5) AI\n6) Другое",
    ], [
        "问题出在哪一阶段？\n1) 安装\n2) 激活\n3) SSH / Deploy\n4) 更新\n5) AI\n6) 其他",
    ]),
    faq_refs=["Q199"],
)

# More ops intents (compact)
for item in [
    ("add_exit", "Deploy", "Add Exit Server", ["exit", "خروجی", "egress"],
     "افزودن سرور Exit (حداکثر ۶؛ نیاز به لایسنس).",
     "Add Exit server (max 6; needs license).",
     "Добавление Exit (макс. 6; нужна лицензия).",
     "添加 Exit 服务器（最多 6；需 License）。",
     ["Q022", "Q013", "Q014"]),
    ("add_tunnel", "Deploy", "Add Tunnel Server", ["tunnel", "تونل", "hop"],
     "Tunnel hop بین Central و Exit (Pro).",
     "Tunnel hop between Central and Exit (Pro).",
     "Tunnel hop между Central и Exit (Pro).",
     "Central 与 Exit 之间的 Tunnel hop（Pro）。",
     ["Q023", "Q109"]),
    ("add_node", "Deploy", "Add Node", ["node", "نود", "xui node"],
     "نود ریموت 3X-UI روی پنل Central (حداکثر ۶، Pro).",
     "Remote 3X-UI node on central panel (max 6, Pro).",
     "Удалённая нода 3X-UI на панели Central (макс. 6, Pro).",
     "在 Central 面板注册远程 3X-UI 节点（最多 6，Pro）。",
     ["Q024", "Q163", "Q147"]),
    ("proxy_settings", "Network", "Proxy Settings", ["proxy", "پروکسی", "socks", "http proxy"],
     "اگر Direct شکست خورد Program Proxy را تنظیم کنید.",
     "If Direct fails, configure Program Proxy.",
     "Если Direct не проходит — настройте Program Proxy.",
     "若 Direct 失败，配置 Program Proxy。",
     ["Q029", "Q030", "Q168"]),
    ("mesh_servers", "Network", "Mesh Servers", ["mesh", "لینک مانیتور", "agent"],
     "ایجنت‌های Link Monitor و وضعیت لینک (Pro).",
     "Link Monitor agents and link status (Pro).",
     "Агенты Link Monitor и статус линков (Pro).",
     "Link Monitor 代理与链路状态（Pro）。",
     ["Q060", "Q173"]),
    ("buy_vps", "Purchase", "Buy VPS", ["vps", "سرور بخر", "partners", "همکاران"],
     "خرید VPS فقط از FoxNext.net → Partners / همکاران.",
     "Buy VPS only via FoxNext.net → Partners.",
     "Покупайте VPS только через FoxNext.net → Partners.",
     "仅通过 FoxNext.net → Partners 购买 VPS。",
     ["Q040"]),
    ("contact_support", "Support", "Contact support", ["support", "پشتیبانی", "hiblackfox", "تیکت"],
     "از تب Contact یا @HiBlackFoxVpn با Device ID و اسکرین پیام دهید.",
     "Use Contact tab or @HiBlackFoxVpn with Device ID and screenshot.",
     "Вкладка Contact или @HiBlackFoxVpn с Device ID и скрином.",
     "通过 Contact 或 @HiBlackFoxVpn，附带 Device ID 与截图。",
     ["Q076", "Q077", "Q193"]),
    ("ai_quota", "License", "AI quota", ["quota", "bfxq", "سهمیه", "شارژ ai"],
     "سهمیه AI جدا از لایسنس است؛ با BFXQ شارژ می‌شود.",
     "AI quota is separate from license; recharge with BFXQ.",
     "AI quota отдельно от лицензии; пополнение BFXQ.",
     "AI quota 与 License 分开；用 BFXQ 充值。",
     ["Q041", "Q080"]),
    ("check_system", "Diagnostics", "Check System", ["diagnostic", "check system", "عیب یابی"],
     "تب Check System عیب‌یابی فقط‌خواندنی محلی است (بدون نیاز به AI quota).",
     "Check System tab is local read-only diagnostics (no AI quota).",
     "Вкладка Check System — локальная диагностика без AI quota.",
     "Check System 为本地只读诊断（不需 AI quota）。",
     ["Q056", "Q145"]),
    ("force_update", "Update", "Force update", ["update", "آپدیت", "force", "min version"],
     "اگر زیر حداقل نسخه باشید، برنامه را از سایت/هاب رسمی Update کنید.",
     "If below minimum version, update from official site/hub.",
     "Если ниже минимума — обновите с официального сайта/хаба.",
     "若低于最低版本，请从官网/Hub 更新。",
     ["Q135", "Q183"]),
    ("delete_history", "Maintenance", "Delete History", ["delete history", "حذف تاریخچه"],
     "Delete History فقط محلی است؛ لایسنس/زبان/حالت می‌ماند؛ VPS پاک نمی‌شود.",
     "Delete History is local only; keeps license/language/mode; does not wipe VPS.",
     "Delete History только локально; лицензия/язык/режим остаются; VPS не трогает.",
     "Delete History 仅本地；保留 License/语言/模式；不清理 VPS。",
     ["Q067", "Q072", "Q165"]),
    ("reset_all_servers", "Maintenance", "Reset All Servers", ["reset all", "پاکسازی ریموت"],
     "Reset All Servers WG/پنل ریموت را برمی‌دارد ولی SSH را نگه می‌دارد.",
     "Reset All Servers removes remote WG/panel but keeps SSH creds.",
     "Reset All Servers снимает WG/панель удалённо, SSH сохраняет.",
     "Reset All Servers 清除远程 WG/面板但保留 SSH。",
     ["Q070", "Q166"]),
    ("install_setup", "Install", "Install Setup", ["install", "نصب", "setup wizard"],
     "Setup را اجرا کنید، زبان و حالت را انتخاب کنید، وارد Operations شوید.",
     "Run Setup, pick language and mode, enter Operations.",
     "Запустите Setup, выберите язык и режим, войдите в Operations.",
     "运行 Setup，选择语言与模式，进入 Operations。",
     ["Q004", "Q065"]),
    ("setup_vs_portable", "Install", "Setup vs Portable", ["portable", "نسخه پرتابل"],
     "Setup پایدارتر است؛ Portable داده را کنار exe می‌گذارد و جابه‌جایی پرریسک‌تر است.",
     "Setup is more stable; Portable keeps data beside exe and is riskier to move.",
     "Setup стабильнее; Portable хранит данные рядом с exe и рискованнее при переносе.",
     "Setup 更稳定；Portable 数据在 exe 旁，移动风险更高。",
     ["Q066", "Q148", "Q196"]),
    ("free_ops_basic", "Modes", "Free Basic operations", ["free", "رایگان", "بدون لایسنس"],
     "بدون لایسنس در Basic فقط Setup Central + Connect SSH + Full Deploy.",
     "Without license in Basic: only Setup Central + Connect SSH + Full Deploy.",
     "Без лицензии в Basic: только Setup Central + Connect SSH + Full Deploy.",
     "Basic 无 License：仅 Setup Central + Connect SSH + Full Deploy。",
     ["Q011"]),
    ("ai_chat_locked", "AI", "AI chat locked", ["ai locked", "activation required", "قفل ai"],
     "چت AI بدون AI Pro یا بدون quota قفل است.",
     "AI chat locks without AI Pro or without quota.",
     "AI-чат блокируется без AI Pro или без quota.",
     "无 AI Pro 或无 quota 时 AI 聊天会锁定。",
     ["Q079", "Q187"]),
]:
    iid, cat, title, kws, fa_s, en_s, ru_s, zh_s, faqs = item
    add(
        intent_id=iid, category=cat, priority="high",
        description=L(title, title, title, title),
        keywords=L(kws, kws, kws, kws),
        sample_questions=qs(
            [f"{title} چیست؟", f"چطور {title}؟", f"{title} کار نمیکنه", f"راهنمای {title}", f"خطای {title}",
             f"{title} کجاست؟", f"چرا {title}؟", f"{title} لازم؟", f"آموزش {title}", f"{title} مرحله به مرحله",
             f"مشکل {title}", f"{title} قفل", f"{title} ارور", f"کمک {title}", f"{title} پرو؟",
             f"{title} basic؟", f"تنظیم {title}", f"بعد از {title}", f"قبل {title}", f"{title}؟"],
            [f"What is {title}?", f"How {title}?", f"{title} not working", f"Guide {title}", f"{title} error",
             f"Where {title}?", f"Why {title}?", f"Need {title}?", f"Tutorial {title}", f"{title} steps",
             f"{title} problem", f"{title} locked", f"{title} fail", f"Help {title}", f"{title} pro?",
             f"{title} basic?", f"Configure {title}", f"After {title}", f"Before {title}", f"{title}?"],
            [f"Что такое {title}?", f"Как {title}?", f"{title} не работает", f"Гайд {title}", f"Ошибка {title}",
             f"Где {title}?", f"Почему {title}?", f"Нужен {title}?", f"Туториал {title}", f"Шаги {title}",
             f"Проблема {title}", f"{title} locked", f"{title} fail", f"Помощь {title}", f"{title} pro?",
             f"{title} basic?", f"Настроить {title}", f"После {title}", f"До {title}", f"{title}?"],
            [f"什么是{title}？", f"如何{title}？", f"{title}不工作", f"{title}指南", f"{title}报错",
             f"{title}在哪？", f"为何{title}？", f"需要{title}吗？", f"{title}教程", f"{title}步骤",
             f"{title}问题", f"{title}锁定", f"{title}失败", f"帮助{title}", f"{title}要Pro吗？",
             f"{title} Basic？", f"配置{title}", f"{title}之后", f"{title}之前", f"{title}？"],
        ),
        short=L(fa_s, en_s, ru_s, zh_s),
        full=L(fa_s + " جزئیات بیشتر در FAQ و User Guide همان زبان.",
               en_s + " See FAQ/User Guide for details.",
               ru_s + " Подробнее в FAQ/User Guide.",
               zh_s + " 详见同语言 FAQ/User Guide。"),
        expert=L("برای جزئیات فیلد به مستندات و NEED_MORE_REVIEW توجه کنید.",
                 "For field-level detail check docs and NEED_MORE_REVIEW markers.",
                 "Детали полей — в docs и метках NEED_MORE_REVIEW.",
                 "字段级细节见文档与 NEED_MORE_REVIEW。"),
        steps=L(["۱. پیش‌نیازها را چک کنید", "۲. عملیات را اجرا کنید", "۳. ترمینال/وضعیت را بخوانید", "۴. در خطا intent خطا را ببینید"],
                ["1. Check prerequisites", "2. Run the operation", "3. Read status/terminal", "4. On error use error intent"],
                ["1. Проверьте prerequisites", "2. Запустите операцию", "3. Читайте status/terminal", "4. При ошибке — error intent"],
                ["1. 检查前提", "2. 执行操作", "3. 查看 status/terminal", "4. 出错时看对应 error intent"]),
        errors=L(["need activate", "need Pro", "SSH/network"], ["need activate", "need Pro", "SSH/network"],
                 ["need activate", "need Pro", "SSH/network"], ["need activate", "need Pro", "SSH/network"]),
        solutions=L(["Registration/Pro", "Connect SSH", "Proxy"], ["Registration/Pro", "Connect SSH", "Proxy"],
                    ["Registration/Pro", "Connect SSH", "Proxy"], ["Registration/Pro", "Connect SSH", "Proxy"]),
        related=["activate_license", "connect_ssh", "need_pro"],
        clarifying=L(["مشکل روی خود قابلیت است یا خطای لایسنس/SSH؟"],
                     ["Is the issue the feature itself or a license/SSH error?"],
                     ["Проблема в самой функции или в license/SSH?"],
                     ["问题是功能本身，还是 License/SSH 错误？"]),
        faq_refs=faqs,
    )

print("TOTAL_INTENTS", len(INTENTS))


def flatten_lang(raw: dict, lang: str, idx: int) -> dict:
    def pick(obj):
        if isinstance(obj, dict) and set(obj.keys()) >= {"fa", "en", "ru", "zh"}:
            return obj[lang]
        return obj

    return {
        "id": f"{raw['intent']}_{lang}",
        "intent": raw["intent"],
        "category": raw["category"],
        "language": lang,
        "keywords": pick(raw["keywords"]),
        "sample_questions": pick(raw["sample_questions"]),
        "short_answer": pick(raw["short_answer"]),
        "full_answer": pick(raw["full_answer"]),
        "steps": pick(raw["steps"]),
        "possible_errors": pick(raw["possible_errors"]),
        "solutions": pick(raw["solutions"]),
        "related_intents": raw["related_intents"],
        "priority": raw["priority"],
        # extensions for smarter bots
        "description": pick(raw["description"]),
        "expert_guide": pick(raw["expert_guide"]),
        "clarifying_questions": pick(raw["clarifying_questions"]),
        "faq_refs": raw.get("faq_refs", []),
        "answer_levels": {
            "level1_short": pick(raw["short_answer"]),
            "level2_full": pick(raw["full_answer"]),
            "level3_expert": pick(raw["expert_guide"]),
        },
        "sort_index": idx,
    }


def main():
    langs = ["fa", "en", "ru", "zh"]
    all_rows = []
    meta = {
        "product": "Black Fox VPN Installer",
        "schema_version": "1.1.0",
        "languages": langs,
        "intent_count": len(INTENTS),
        "facts": {
            "free_basic_ops": ["setup_central", "connect_ssh", "full_deploy"],
            "max_exit_servers": 6,
            "max_nodes": 6,
            "pro_ne_ai_pro": True,
            "tabs": ["Operations", "Check System", "View", "Settings", "Registration", "Contact"],
            "vps_purchase": "FoxNext.net → Partners only",
        },
        "sources": [
            "Documentation/",
            "AI_Knowledge_Base_Multilingual/",
            "Screenshots/",
        ],
    }

    for lang in langs:
        rows = [flatten_lang(raw, lang, i) for i, raw in enumerate(INTENTS)]
        path = OUT / f"intents_{lang}.json"
        payload = {"meta": {**meta, "language": lang}, "intents": rows}
        path.write_text(json.dumps(payload, ensure_ascii=False, indent=2), encoding="utf-8")
        print("wrote", path.name, len(rows), path.stat().st_size)
        all_rows.extend(rows)

    all_path = ROOT / "all_languages_database.json"
    all_payload = {
        "meta": meta,
        "language_detection_hints": {
            "fa": ["می‌", "است", "چطور", "لایسنس", "فعال", "؟"],
            "en": ["how", "what", "license", "activate", "error", "?"],
            "ru": ["как", "что", "лиценз", "ошибк", "почему", "?"],
            "zh": ["如何", "什么", "激活", "错误", "为什么", "？"],
        },
        "routing": {
            "prefer_language_file": "intents/intents_{lang}.json",
            "fallback_language": "en",
            "ambiguous_intent": "ambiguous_app_broken",
            "knowledge_markdown": "AI_Knowledge_Base_Multilingual/{LangFolder}/",
        },
        "intents": all_rows,
    }
    all_path.write_text(json.dumps(all_payload, ensure_ascii=False, indent=2), encoding="utf-8")
    print("wrote", all_path.name, len(all_rows), all_path.stat().st_size)

    # master multilingual (nested) for editors
    master_path = ROOT / "intents_master_multilingual.json"
    master_path.write_text(json.dumps({"meta": meta, "intents": INTENTS}, ensure_ascii=False, indent=2), encoding="utf-8")
    print("wrote", master_path.name, master_path.stat().st_size)


if __name__ == "__main__":
    main()
